### ISSUE TITLE
Expose machine's states as parent-level booleans

### ISSUE THREAD

**Issue by NerdCowboy** [davidkpiano/xstate#1027]
## Bug or feature request?
Feature Request

## Description:
Expose machine's states as parent-level booleans. Mostly just want for syntactic sugar as writing `state.isLoading` in JSX/templates is easier to write/read than `state.matches('isLoading')` 

Happy to try my hand at a PR, but wanted to see if it's something you like first.

## (Feature) Potential implementation:
Would need to loop through a machine's states and spread the resulting object at the parent-level
```
PSEUDO CODE:
const statesToSpread =  machineStates.map(machineState => {
  return [machineState]: matches(machineState)
}
....

state = {
  actions: [],
  activities: {},
  …etc,
  ...statesToSpread
}  
```

**Comment by davidkpiano** [comment]
This is something that will likely not be built into core XState, but you're more than welcome to create a package for this in user-land!

The reasoning: `state.isLoading`, using `is` as a convention for "**is** in this state", can bet better represented by something non-convention-based, like `state.is('loading')`, which... is essentially what `state.matches('loading')` is. And `matches` is a better descriptor because the state value can be `{ loading: 'user' }` in which `'loading'` should still match.

Honestly, the whole purpose of state machines is to move away from `isLoading`, and these should be _derived_ from the state (purely for developer convenience), instead of baked-in.
