### ISSUE TITLE
Suggestion: add `.state` to `@xstate/fsm` service

### ISSUE THREAD

**Issue by alexreardon** [davidkpiano/xstate#1080]
an intepreted service for an `xstate` machine as a `.state` property which is pretty useful to be able to grab. `@xstate/fsm` tracks this state (`let state = ..`), but does not expose it.

Context: I am looking to create an alternative `useService` for react and getting the state for initial render is tricky as you need to setup a subscriber and grab the state in the first render.

**Comment by Andarist** [comment]
Could you give some context on why do you want to implement an alternative `useService`?

**Comment by davidkpiano** [comment]
We're going to be refactoring to use what's called an `ActorRef` (if you are familiar with Akka, same concept), which will have the notion of a `.current` value on it (which can be considered the locally "cached" latest value that the actor emitted).

So let's hold off on that so that `.state` (or `.current` etc.) isn't just an ad-hoc property on some object and rather part of a standard `ActorRef` interface. Working on this soon!

**Comment by alexreardon** [comment]
Thanks @davidkpiano. I was having some typing issues with `useService` and I also wanted to explore what writing one could look like. Today you need to do something like this to have the initial value populated on first render:

1. create the machine
2. create a service by interpreting the machine. Don't start the machine!
3. add a subscriber to the machine.
4. start the machine
5. read the value given to the subscriber

After initial render things are a bit easier as you can just cause a render based on the subscriber being called

**Comment by alexreardon** [comment]
Amazing! Thanks @davidkpiano 👏 

Is there a way I can consume that change?

**Comment by Andarist** [comment]
Not yet, but we are going to cut a new release soon.

**Comment by Yuyz0112** [comment]
Any chance to schedule a new release with this patch?

**Comment by davidkpiano** [comment]
@Yuyz0112 This has been published
