### ISSUE TITLE
[@xstate/react] Issue when updating a machine while rendering that affects another component

### ISSUE THREAD

**Issue by IceSentry** [davidkpiano/xstate#1117]
**Description**
I'm not sure how to explain it, but I've made a code sandbox that shows the issue. The issue happens when calling send() from a component that is being rendered. When that send triggers a change and another component is looking at the state react throws an error.

**Expected Result**
no error thrown

**Actual Result**
calling send() raises an error that links to https://fb.me/setstate-in-render

**Reproduction**
https://codesandbox.io/s/xstate-setstate-render-bug-6455d?file=/src/App.tsx

**Additional context**

It's possible that I'm just not using the library properly or that the issue happens in react-router, but the call stack points to send() as being the issue

**Comment by IceSentry** [comment]
Sorry, I was using the send of the service directly instead of useService()

**Comment by IceSentry** [comment]
I closed it too fast, the issue still happens even when using send() from the useService() hook

**Comment by Andarist** [comment]
Why do you want to send an event to a machine **during** rendering? This seems like a huge React anti-pattern. Send is still sort of a side effect so it shouldn't be used like this.

**Comment by IceSentry** [comment]
To do some things like in the code sandbox. I want to show the current state of the machine in another component that isn't the one that triggers the send. If you know of a better way to do that I'm opened to suggestions.

**Comment by IceSentry** [comment]
Oh, I realize my mistake now, I should have put the send in a useEffect()

**Comment by IceSentry** [comment]
Yep, I updated my sandbox and useEffect() fixed it, I'm not sure hwo I missed that sorry...

**Comment by hipstersmoothie** [comment]
@Andarist 

> Why do you want to send an event to a machine during rendering? This seems like a huge React anti-pattern.

This is actually opposite from the advice from the react team. They do suggest you update things during render rather than in effects. I ran into a similar problem to this thread where I fire an event during render based on some props. Ideally I'd like to not have logic to check the state to see if I should fire the event during render. 

https://beta.reactjs.org/learn/you-might-not-need-an-effect#adjusting-some-state-when-a-prop-changes
What I have to do right now

![CleanShot 2022-09-16 at 17 11 35](https://user-images.githubusercontent.com/1192452/190832399-90dfe2d2-efc3-4d98-87d8-d7d28870aeeb.png)

What I want to do do. The enabled and disable active don't do anything most of the time since they're not in a state where they should do something.

![CleanShot 2022-09-16 at 17 13 00](https://user-images.githubusercontent.com/1192452/190832449-6e194d26-5cbb-4f68-bbf4-b4fd3e6427a4.png)
