### ISSUE TITLE
Angular xState example

### ISSUE THREAD

**Issue by peterhe2000** [davidkpiano/xstate#1196]
Thanks for a awesome package. Thanks for the great work. 
I am also a huge fans of FSM.
However I am struggling to find a good example of Angular working with xState. 
Is there a recommendation? 

List i found so far. Not many angular xstate example for some reason.
Seems each of those example got it's own implementation. 
Hope there is a standard which xstate team may suggest with.
https://stackblitz.com/edit/xstate-angular-table
https://stackblitz.com/edit/angular-xstate-http?file=src%2Fapp%2FloadMachine.ts
https://medium.com/angular-athens/working-with-state-machines-in-angular-2817441e26bf

**Comment by timdeschryver** [comment]
I think a simple machine can be implemented with the [RxJS recipe](https://xstate.js.org/docs/recipes/rxjs.html).

I also experimented with XState in Angular and came up with a [POC implementation](https://gist.github.com/timdeschryver/dcdeefdba43bef7134c8249e8257dae7) that was inspired by the `useMachine` hook from `xstate/react`. This implementation also takes a stream of events, instead of invoking the statemachine with the `send` method.

**Comment by peterhe2000** [comment]
Thanks @timdeschryver  Most of angular example seems come from you.
For ur POC implementation, how do i send machine next event from XStatePocComponent? 
Also where can i find ur machine which i can play in https://xstate.js.org/viz/?

**Comment by timdeschryver** [comment]
@peterhe2000 sending events is done via ["input observables"](https://gist.github.com/timdeschryver/dcdeefdba43bef7134c8249e8257dae7#file-table-component-ts-L58).
Seems like I didn't add the machine to the gist, I don't have that code anymore - sorry.
