### ISSUE TITLE
[React] Duplicate machine execution with React.StrictMode

### ISSUE THREAD

**Issue by FredyC** [davidkpiano/xstate#1237]
**Description**
The core of the problem is that with `useMachine` a machine _instance_ is created twice and then follows whatever is on its initial path (invocation, actions...). Ultimately, this causes a cascade in my code where two WebSocket connections are created and receive events. Everything then happens twice.

**Expected Result**
An only a single instance of a machine should exist.

**Actual Result**
Two machine instances are executed separately.

**Reproduction**
I tried to use CodeSandbox but due to the unreleased fix for "actions in effects by default" I could not reproduce it.

https://codesandbox.io/s/sharp-waterfall-14m3c?file=/src/App.js

I made a repo instead which contains the latest `@xstate/react` built from the `master` branch.

https://github.com/FredyC/xstate-react-multiple-services-bug

It's just CRA, so as usual `yarn install` & `yarn start`. When you run that, in the console, you can see.

![image](https://user-images.githubusercontent.com/1096340/84564834-0ecf7300-ad65-11ea-86d1-78d13acdf667.png)

**Comment by FredyC** [comment]
Upon initial inspection, the culprit seems to be in `useConstant` which is executed twice and that happens because of `React.StrictMode`. Once I remove that, it works as expected.

Honestly, I haven't really looked into this React future stuff, so I am not sure how to properly tackle that.

**Comment by FredyC** [comment]
Yea, I guess this isn't something that can be solved on XState side. React does that in DEV mode only. But it certainly makes debugging a hell to see all log outputs twice :/

**Comment by Andarist** [comment]
Yes, this is related to React's Concurrent Mode - there is no guarantee that your components will render just one time and StrictMode in DEV simulates this by **always** rendering your components twice before mounting them to help you notice such problems.

As you have concluded - this is not something that we can really tackle on our side, it's a byproduct of how React works (or will work in the future). This is pretty much the same situation as you would get with any other code that would be structured this way, it's not by any means exclusive to `@xstate/react`. Example:
```js
class Foo {
  constructor() {
    console.log('hi!')
  }
}

function Comp() {
  // using useConstant doesn't really matter here, I'm just using it for illustration purposes as you already know what it does
  const foo = useConstant(() => {
    return new Foo()
  })
}
```

React's mantra is to not perform side-effects in render and this is exactly what happens here. Managing this is consumer's responsibility as it is when integrating any other code with React.

**Comment by FredyC** [comment]
What seems to be a viable workaround if instead of using "entry" or transient transitions to basically _boot up_ the machine with event sends from `React.useLayoutEffect`. That way the first _verification_ instance is not used and only the latter one is.

Could be perhaps bake something like that inside `@xstate/react` (in DEV mode only)? It could be enough to `.start()` machine in `React.useLayoutEffect`. I can try to send in the PR.

**Comment by Andarist** [comment]
> Could be perhaps bake something like that inside @xstate/react (in DEV mode only)?

Please note that this "problem" is not exclusive to the DEV mode - it's only surfaced 100% of the time thanks to the StrictMode, but this could happen at any time when using Concurrent Mode. Concurrent Mode is not yet ready to be used, but its semantics around this are clear and we want to be ready for it - so no changes will be required from our consumers when it finally gets released.

> It could be enough to .start() machine in React.useLayoutEffect. I can try to send in the PR.

Starting a machine later than in render is slightly problematic as some resources are not ready to be used then when rendering. Most notably `service.children` are not available and people pass those to inner components to consume them with `useService` there.

**Comment by FredyC** [comment]
> Starting a machine later than in render is slightly problematic as some resources are not ready to be used then when rendering. Most notably `service.children` are not available and people pass those to inner components to consume them with `useService` there.

Yea, there are always tradeoffs, but semantically it would even make more sense to start the machine as a side effect.

Ultimately, it might be interesting to utilize Suspense to suspend rendering until those resources are ready. For example instead of accessing `service.children` there would be `service.getChild(...)` which would throw a Promise if not ready yet. It would of course require some global-ish cache as those promises cannot live in React component.

**Comment by davidkpiano** [comment]
I was able to juggle some things around `useMachine` and get this to work. The only difference (which shouldn't affect apps) is that the first `[state, ...]` that comes from `useMachine(...)` comes from the non-interpreted created `machine`, _not_ the created `service` (but the `service` uses that `machine`).

The main issue is/was that `service.start(...)` is a side-effect that is being called in `useConstant(...)`, so I moved that to `useEffect`.

**Comment by FredyC** [comment]
Oh wow, did not expect such a fast fix. Thank you, David. 🙌 I can confirm it works. I have updated the repo above with your code.

**Comment by davidkpiano** [comment]
By "it shouldn't affect apps", the caveat is that if you invoke a service on initialization, you should _not_ expect that service to be present on first render... I think.

**Comment by davidkpiano** [comment]
There is still the issue with immediately invoked services.

Funny enough, this thread you created a few months back: https://github.com/facebook/react/issues/15317 is part of the issue. If we could have an effect that is executed on first render (instead of after), it would solve this issue.

**Comment by Andarist** [comment]
I must say that I haven't read the whole linked thread just yet as it's quite lengthy, but it mostly seems to describe a slightly different issue than we have here. Of course, they are overlapping in some parts and a cleanup hook for canceled renders would make our lives easier.

React team is mostly concerned about rendering deopts here which is a fair concern from the point of view. We don't quite suffer from those issues here as badly. Phil Pluckthun mentions there:
> We essentially stop listening between the first render (mount) and the commit phase. So this only works in our case because we can stop all side-effects in-between both phases.

And this is essentially our exact situation - we only might deopt rendering if something has changed between render and mount which shouldn't really happen.

The only conceptual problem with the current way (`start()` in render) is that it's not obvious for consumers that they should model their machines with CM in mind. It's not as apparent that they are restricted (in terms of side effects they would like to perform) in the very same way as hand-written code because machines are mostly abstracted away from React. For the very same logic hand-written the problem would be much more apparent and people knowing React semantics would handle it OK most of the time.

I don't really have a good answer to this problem because it's a hard one due to what requirements CM has. We probably could figure out how to create fake children services for the initial render that could be read in render but this would potentially mean that we would have to deopt rendering (double render problem) of all components with machines that have children. Any form of implicit delaying any actions is also magical and while maybe it would be easier to use it could potentially deteriorate the mental model and debugging experience in certain situations, so there are definitely tradeoffs to be considered here.

Should `@xstate/react` "work like React" or should it "work like XState"? Which of those sides are more important here?
