### ISSUE TITLE
@xstate/fsm is generating es5 for the es/ build

### ISSUE THREAD

**Issue by mreinstein** [davidkpiano/xstate#1412]
There are no javascript runtimes that support es modules but lack es6 support. When I look in `packages/xstate-fsm/es/index.js` I see that it was generated with es5 as an output.

This seems to be due to rollup's config file setting `tsconfig: 'tsconfig.compat.json'` for both the umd and esm builds. Is this intentional or an oversight?

**Comment by Andarist** [comment]
This is somewhat a common misconception about `"module"` field. Rollup was one of the first to adopt `"module"` (previously `"jsnext:main"`) and this is what [their old wiki page](https://github.com/rollup/rollup/wiki/pkg.module) says about it:
> pkg.module will point to a module that has ES2015 module syntax but otherwise only syntax features that the target environments support.

So as you can see one shouldn't link module syntax to other syntax features for the purpose of this field. That being said - we could decide to transpile to the newer syntax level than es5, it's up to us. It's not a common choice in the community though and I'm somewhat scared to be one of "early adopters" in this regard. People often ignore transpilation of the `node_modules` in their bundler configs as this is often advised by various perf guides and similar. So by upgrading our syntax we would make things harder for many people that are following that advice and who need to support older envs (like IE11). Not saying that's this is some kind of a decisive factor for this decision but it's certainly something that we should at least consider.

Anyway - I would consider this to be a breaking change and it would require to be included in a new major version (so not now as we don't plan to release a new major just yet). This is the same as upgrading `pkg.engines` for node-specific packages - it's always a breaking change.

**Comment by mreinstein** [comment]
> This is somewhat a common misconception about "module" field

We shouldn't set the `module` field in v5;  That was a proposal put forward by rollup for how to deal with es modules without clobbering the `main` field in `package.json` prior to it being standardized in node. It has been superseded by setting `"type": "module"` in `package.json`. (see https://nodejs.org/dist/latest-v12.x/docs/api/esm.html#esm_package_json_type_field )


> we could decide to transpile to the newer syntax level than es5, it's up to us.
> It's not a common choice in the community though

It's not a common choice in the community because unflagging esm support in node and removing the scary warning has only happened quite recently, in the last few months: https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#2020-05-26-version-12170-erbium-lts-targos



> one shouldn't link module syntax to other syntax features for the purpose of this field.

There are no javascript runtimes that support es modules, but lack es6. There is no point in generating es modules that use that older syntax. I would go so far as to say it could be considered harmful transpiling down to an older es version. At work our frontend code is able to feature detect when a browser supports es modules, and we load the newer code path written in es6. On average it's about 30% less lines of code. We don't want to ship modules written in es5 to newer browsers. That _is_ a common community choice, and it's not ideal.

> by upgrading our syntax we would make things harder for many people that are following
> that advice and who need to support older envs (like IE11)

The code that xstate/fsm provides for ie11 already requires a bundler (both umd and es builds.) I don't think this changes that. Code intended for bundling still needs to be run through a bundler.

**Comment by Andarist** [comment]
> It's not a common choice in the community because unflagging esm support in node and removing the scary warning has only happened quite recently, in the last few months: https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#2020-05-26-version-12170-erbium-lts-targos

I don't feel that those are at all related - syntax itself is not tied to the module format and there are some packages (node-only mostly) that have decided to use es6+ syntax in the shipped code, not looking at all at the CJS/ESM drama because those are 2 different things. You can totally use newer syntax while still be using CJS format.

> There are no javascript runtimes that support es modules, but lack es6. There is no point in generating es modules that use that older syntax.

But there absolutely is a point in that - there are multiple targets one can think of and even if the final target environment doesn't support ESM there is still a middleman processor (like a bundler) between the package itself and the final app~. If a module syntax is important for such a middleman processor (and it is) then it's a totally valid choice to provide ESM files using only ES5 syntax besides the export/import statements.

>  At work our frontend code is able to feature detect when a browser supports es modules, and we load the newer code path written in es6. On average it's about 30% less lines of code. We don't want to ship modules written in es5 to newer browsers. That is a common community choice, and it's not ideal.

With this I can agree - it's not ideal at all. I'm just saying that shipping newer code by default is a different decision, not related to the module format and that it can be done, but should be evaluated carefully, because as package maintainers we have responsibilities for a lot of users with different use cases, different capabilities of customizing their build processes, etc. It's important for us to think about those. Changing the syntax level is also a breaking change so we only should be thinking about this when releasing a new major versions.

> The code that xstate/fsm provides for ie11 already requires a bundler (both umd and es builds.) I don't think this changes that. Code intended for bundling still needs to be run through a bundler.

Yes, it's different matter though if something is meant to be processed by a bundler to load files/concatenate them etc than if it meant to be processed by a transpiler plugged into that bundler. Problem is that ignoring `/node_modules/` from transpilation has been a recommendation for **a very long time** and there are many people doing just that. Even if this can be changed on their side it's still something that they will have to do and many might not know how or might break things in the process of changing this.

I would also like to see advancements in this field, but I don't see any in the community as a whole and I don't particularly feel like being a precursor here.

**Comment by mreinstein** [comment]
> I don't feel that those ..

> I don't particularly feel like being

Then I guess there's not much point in discussing it.  Most of these points are feelings and not hard facts. If you don't want to produce esm that's certainly your choice.
