### ISSUE TITLE
onTransition is not invoked the 2nd time a state machine is run

### ISSUE THREAD

**Issue by RavitHrr** [davidkpiano/xstate#1423]
**Description**
I'm using onTransition on an interpreted state machine that works fine for all the states the first time the state machine runs, it reaches a type final state.
Then, I'm starting the same state machine again. All the states works fine, but onTransition is not invoked.

**Expected Result**
onTransition should be invoked on every transition, even if the state machine has been restarted.

**Actual Result**
onTransition is not invoked the second time I'm calling start() on the interpreted state machine.

Thank you!

**Comment by davidkpiano** [comment]
✏️ Please create a [CodeSandbox (XState template)](https://codesandbox.io/s/xstate-example-template-qcwed) reproduction of this. Thanks!

**Comment by davidkpiano** [comment]
On further investigation, this is working as intended. When a machine is started, the registered listeners are active. When it is stopped, the listeners are inactive and _disposed_ (otherwise, this would be a memory leak).

Since it's impossible to predict the future and know that these listeners will be needed again, when a machine is restarted, it is necessary to _reregister_ the listeners.

Restarting a machine should also be avoided. When a machine is stopped, if you want to "restart it", you should instead start a new instance of the service:

```js
const listener = (state) => console.log(state);

const service = interpret(machine)
  .onTransition(listener)
  .start();

// ...

service.stop();

// ...

// Restart
const newService = interpret(machine)
  .onTransition(listener) // register the listener again
  .start();
```
