### ISSUE TITLE
More FSM type checking in xstate 4.0

### ISSUE THREAD

**Issue by laurentpierson** [davidkpiano/xstate#178]
## Bug or feature request?
Feature request

## Description:
I have tested xstate 4.0.0-8 I see it is now possible to ensure more typing of our FSMs, which is great news. Thanks to StateSchema & EventObject, we can make now make sure the initial state, state names and 'on' transitions contain acceptable values. But the state to which a transition refers to is unfortunately still a string. Do you plan on adding type checking for those too?

## Link to reproduction or proof-of-concept:

```
describe('StateSchema', () => {

	type FsmStates = 'first' | 'second' | 'error';

	interface FsmSchema {
		states?: {
			[key in FsmStates]: FsmSchema;
		};
	}

	type FsmEvents =
		| { type: 'onSuccess' }
		| { type: 'onError' };

	const fsm = Machine<undefined, FsmSchema, FsmEvents>({
		key: 'testFsm',
		initial: 'first', // type checked against FsmStates
		states: {
			first: { // type checked against FsmStates
				on: {
					onSuccess: 'second', // onSuccess is of type FsmEvents, but no type checking for 'second'
					onError: 'error_typo' // onError is of type FsmEvents, but no type checking for 'error_typo'
				}
			},
			second: { // type checked against FsmStates

			},
			error: { // type checked against FsmStates

			}
		}
	});
});
```

**Comment by davidkpiano** [comment]
The main issue with that is that targets can be:

- Relative (default): `'second'`
- Relative descendants: `'.foo.bar'` or `'second.foo'` ⚠️ 
- IDs `'#secondState'`

The first is easiest type against, but the second introduces issues, and is not feasible unless xstate can generate a comprehensive state schema that adds all the possible descendant states with the dot-syntax. IDs are _doable_ but a bit trickier (since the `StateSchema` is recursive, and the IDs are defined on the nested state schemas).

There's a couple ways we can resolve the relative descendants issue:
- Forbid their usage unless you explicitly add them in your state schema
- Type transition targets as `string` if no transition states are defined (just like how events are typed as `EventObject` if not specified)
- Introduce a declarative syntax for these relative states, e.g.:

```
on: {
  SUCCESS: {
    // instead of SUCCESS: '.bar.baz'
	target: { relative: ['.', 'bar', 'baz'] }
  }
}
```

Which can be sugared: `SUCCESS: relative(['.', 'bar', 'baz'])`. Just an idea, still not sure if I like it.

What are your thoughts?

**Comment by laurentpierson** [comment]
Hi David,

Thanks for your quick response.

So far we have only used relative (default) targets in our project.

I am not in favour of forbidding relative descendants usage (unless explicitly added to state schema) because I have the feeling the state schema and the actual MachineConfig will look more and more like 2 versions of the same thing, meaning one change to the FSM will require a change to the schema.

I was going for a less constrained approach where we can make at least sure that all states, transitions & targets match with some union types or enums so that we can avoid typos that would only be discovered at runtime. This is not as powerful as a complete schema validation but it's more flexibe IMHO.

**Comment by davidkpiano** [comment]
I'm confused - that's asking for two different things. If you don't want to explicitly add state targets (relative or otherwise) to the schema, then you will need to allow `... | string` which means that `'foo.bar.baz'` and `'someTypoState'` will both be equally valid.

What I'm saying is if you want to use `'foo.bar.baz'`, you need to explicitly add it, e.g., `'foo' | 'something' | 'foo.bar.baz' | etc...`

**Comment by laurentpierson** [comment]
Sorry for the confusion.

For Relative descendants:  `SUCCESS: relative(['.', 'bar', 'baz'])` looks fine to me if it can allow us to type the Relative (default) (which we're mostly using).

So, for me the following code change could do the trick:
 
```
export declare type TransitionsConfig<TContext, TEvents extends EventObject> = {
    [K in TEvents['type'] | BuiltInEvent<TEvents>['type']]?: string | TransitionConfig<TContext, TEvents extends {
        type: K;
    } ? TEvents : EventObject> | Array<TransitionConfig<TContext, TEvents extends {
        type: K;
    } ? TEvents : EventObject>>;
}; 
``` 
changed to
```
export declare type TransitionsConfig<TContext, TEvents extends EventObject, TTarget=string> = {
    [K in TEvents['type'] | BuiltInEvent<TEvents>['type']]?: TTarget | TransitionConfig<TContext, TEvents extends {
        type: K;
    } ? TEvents : EventObject> | Array<TransitionConfig<TContext, TEvents extends {
        type: K;
    } ? TEvents : EventObject>>;
};
```

Maybe string could be default unless specified?

**Comment by klemola** [comment]
I would love to be able to opt-in for enforcing targets to be states instead of strings, and similarly enforcing `activities` keys 👍

**Comment by davidkpiano** [comment]
> I would love to be able to opt-in for enforcing targets to be states instead of strings

You can: https://xstate.js.org/docs/guides/ids.html#avoiding-strings

> and similarly enforcing activities keys

Coming 🔜 in 4.7?

**Comment by klemola** [comment]
Thanks, lovely!

**Comment by davidkpiano** [comment]
We are renovating the way that types are checked in the upcoming V5 (`next` branch), so I'll close this for now.
