### ISSUE TITLE
xstate-react: Uncaught TypeError: Cannot read property 'toObserver' of undefined

### ISSUE THREAD

**Issue by dimitardanailov** [davidkpiano/xstate#1948]
**Description**

I've been working on legacy project. The project uses angularjs two months ago: My team successfully implemented React, Xstate and Xstate and React. The project doesn't have a build tool. My team uses direct import example: 

```javascript
<script crossorigin src="https://unpkg.com/xstate@4/dist/xstate.js"></script>
```

```javascript
<script crossorigin src="https://unpkg.com/@xstate/react/dist/xstate-react.umd.min.js"></script>
```

Versions are: 
- https://unpkg.com/@xstate/react@1.3.0/dist/xstate-react.umd.min.js
- https://unpkg.com/xstate@4.16.1/dist/xstate.js

The error output is: 
![Screenshot 2021-02-18 at 22 51 15](https://user-images.githubusercontent.com/2182018/108419955-d8bf8880-723b-11eb-8f98-c3915815d600.png)

These pull request can be helpful source of true:
https://github.com/davidkpiano/xstate/pulls?q=is%3Apr+author%3Adimitardanailov+is%3Aclosed

**Comment by davidkpiano** [comment]
Hey @dimitardanailov, since the recommended way to consume XState and `@xstate/react` is within projects that have some sort of build step and make use of `import { ... } from '@xstate/react'`, I will need your help in pinpointing what the error is, and what the potential fix is.

Can you please investigate this and come up with a proposed fix?

**Comment by dimitardanailov** [comment]
@davidkpiano and @Andarist 

Thank you very much for the fast response. The issue is fixed !!!
