### ISSUE TITLE
Possible inconsistency with actions values?

### ISSUE THREAD

**Issue by geart891** [davidkpiano/xstate#1957]
**Description**
`actions`, `entry`, `exit`, etc. properties can take `undefined` as a value but when array with falsy value like `[undefined]` or `[null]` xstate action breaks. (it doesn't break with empty object `[{}]`).

Use case for this is when creating a lot of dynamic action creators, instead of return `undefined` for noop action, empty `{}` must be returned for xstate to not break.
**Expected Result**
All action keys should be consistently accepting falsy value and not breaking.

**Actual Result**
it breaks. 
**Reproduction**
[codesandbox](https://codesandbox.io/s/practical-christian-yxs5t)

**Additional context**

![image](https://user-images.githubusercontent.com/27849964/109043100-51c75000-7714-11eb-9019-0410b408014f.png)
I traced it back to:
![image](https://user-images.githubusercontent.com/27849964/109043233-74596900-7714-11eb-9c69-27140ed3775e.png)

**Comment by davidkpiano** [comment]
This is expected behavior. If you're using VS Code, please add `// @ts-check` to the top, and it should highlight that as an error for you.

XState does not do runtime checks to check if the actions are valid actions, as that should ideally be type-checked.

You can create a helper in userland to assist with this:

```js
const filterActions = (actions) => actions.filter(Boolean);

// ...
actions: filterActions([undefined, null])
```
