### ISSUE TITLE
strict mode should throw error on unknown transition

### ISSUE THREAD

**Issue by foray1010** [davidkpiano/xstate#2012]
**Description**
Here is an example of my fsm, I would expect only the `alive` can be `kill`ed, otherwise it is a bug. But in current strict mode, it is allowed

```js
const {createMachine} = require('xstate')

const fsm = createMachine({
  strict: true,
  initial: 'alive',
  states: {
    alive: {
      on: {
        kill: 'dead',
      }
    },
    dead: {
      on: {}
    },
  }
})
console.log(fsm.transition('dead', 'kill').value) // => `dead` instead of error
```

I understand that xstate allows to explicitly define a transition as `undefined` to bypass throwing error. But if it is not specified as `undefined`, I think it should be an error because it is not intended to use this way.

**Expected Result**
`Error: Machine '(machine)' does not accept event 'kill'`

**Actual Result**
return `dead` instead of error

**Reproduction**
see my script above

**Additional context**
xstate: 4.16.2

**Comment by Andarist** [comment]
This is not necessarily the expected behavior. Machines just ignore unhandled events. I believe that we should simplify things in the next major version and we shouldn't have a strict and non-strict mode. The behavior should just always be the same and throwing at all times doesn't sound like something we'd like to introduce.

`SOME_EVENT: undefined` serves a slightly different purpose - it prevents a transition defined in the ancestor from happening (resembles DOM event bubbling and `event.stopPropagation()`).

**Comment by davidkpiano** [comment]
> I believe that we should simplify things in the next major version and we shouldn't have a strict and non-strict mode. The behavior should just always be the same and throwing at all times doesn't sound like something we'd like to introduce.

Agree - `strict` mode is something that will probably go away in v5, as there are better ways to get the same strictness.

Currently, strict mode is for events that are not defined anywhere in the machine; in this case, `KILL` is defined, just not in that state. The machine is still correct, too: doing that action repeatedly means the thing is still in the `dead` state (how morbid 😆).

You can add a wildcard transition for errors, if you'd like:

```js
on: {
  '*': {
    actions: () => { throw new Error('...') }
  }
}
```
