### ISSUE TITLE
statecharts.io/inspect visualizer - missing scroll bar

### ISSUE THREAD

**Issue by Mrcdkk** [davidkpiano/xstate#2123]
**Description**

I miss a scroll bar when I visualize a large Xstate machines in the statecharts.io/inspect visualizer. 
Are there any secret key short cuts?
Currently I can only zoom out, but this doesn´t really work well at the events list.

**Comment by davidkpiano** [comment]
You can scroll around to move the machine - have you tried that? Even if scrollbars aren't visible, it should still work.

**Comment by Mrcdkk** [comment]
You are right. I can scroll with the mouse wheel up and down the visualisation of the machine. And I can scoll up dand down also the 'Event' and 'Sequence' view.  

But I cannot scroll up down the the 'State' view and I cannot move left and right the visualisation of the machine.

**Comment by davidkpiano** [comment]
I think this was mentioned in here: https://github.com/davidkpiano/xstate/discussions/1430

If not, can you please add it?

I'm working on completely overhauling the visual output for the inspector in preparation for the visual creator/editor (which is why it's taking a while), so that will likely be fixed when that is finished.
