### ISSUE TITLE
Entry action not fired when using service.start in specified state

### ISSUE THREAD

**Issue by mr-bjerre** [davidkpiano/xstate#2183]
**Description**
I'm starting an interpreter in a specified state by

```javascript
const service = interpret(machine);

service.start("inactive");
```

**Expected Result**
I'd expect the entry action in `inactive` to be fired right away.

**Actual Result**
The `entry` is action only fired when transitioning to `inactive` not when starting in `inactive`

**Reproduction**

Here is a [CSB](https://codesandbox.io/s/gracious-sara-rf37y?file=/src/index.js:551-671) demonstrating the behaviour.

**Comment by mr-bjerre** [comment]
It's definitely a valid point. I'd argue that both options make sense to me though. 

As a minimum we should add a note in the docs about it. What do you think? Either in `entry` or in `.start`

**Comment by Andarist** [comment]
Question - could u describe ur concrete use case in more detail?

**Comment by davidkpiano** [comment]
@mr-bjerre This happens because `"inactive"` is interpreted as a state with no actions. 

You can resolve it like this:

```js
service.start(machine.resolveState(State.from("inactive")));
```

It's a bit awkward, because this isn't the normal way to do it. Ideally, when restoring state, the state comes from a previous interpretation of the machine, so you don't have to do `State.from` and `machine.resolveState`.
