### ISSUE TITLE
Typescript - Context type error when using model.InitialContext

### ISSUE THREAD

**Issue by BrunoQuaresma** [davidkpiano/xstate#2338]
**Description**
Context is returning type error when using model.initialContext 

**Expected Result**
 No type error

**Actual Result**
A type error

**Reproduction**
Here is a codesanbox https://codesandbox.io/s/late-shadow-kelkd?file=/src/dragMachine.ts

**Comment by davidkpiano** [comment]
Will be fixed in #2334

**Comment by BrunoQuaresma** [comment]
Perfect, thank you.

**Comment by Andarist** [comment]
I don't think that #2334 will fix this entirely.

The problem is that the first overload has failed to match and the second has been tried - which didn't match either and resulted in a cryptic error. This might get fixed with #2334

There is more to it though. Our types are not smart enough (this is a *very* hard thing to do at the type level) to know what kind of events `implementations.actions` can take. Therefore you can't use actions that can only handle specific events there - those actions, currently, need to handle all possible events. This is the only way to actually ensure type safety there (at the moment).

For some reason, the inference goes all bonkers there though if `actions` are defined within the `createMachine` call. If we move their definition out of this call then correct~ types are assigned to the resulting object and we can pass it freely as the second argument to the `createMachine` call. Please see the corrected codesandbox: https://codesandbox.io/s/relaxed-framework-9z1ez?file=/src/dragMachine.ts

**Comment by davidkpiano** [comment]
Right; this will be fixed for actions that do _not_ restrict event types in `actions` (per @Andarist's explanation)

The workaround, for now, is to specify those `model.assign(...)` actions inline.

**Comment by BrunoQuaresma** [comment]
Using @Andarist as base, how could I make the `guards` on `implementations` be typed? https://codesandbox.io/s/serene-sunset-c8wun

**Comment by davidkpiano** [comment]
> Using @Andarist as base, how could I make the `guards` on `implementations` be typed? https://codesandbox.io/s/serene-sunset-c8wun. If I need to make it manually, how can I get the `Event` type from a model?

We should make a helper for this, but you can do this:

```ts
  guards: {
    isValid: (ctx: ModelContextFrom<typeof dragModel>, event: ModelEventsFrom<typeof dragModel>) => {
      return false;
    }
  }
```

**Comment by BrunoQuaresma** [comment]
The `ModelSomethingFrom` is quite helpful tho, thanks.
