### ISSUE TITLE
Deprecate Null Events

### ISSUE THREAD

**Issue by hnordt** [davidkpiano/xstate#279]
Null events are cool, but maybe we could enhance `onEntry` as an idiomatic alternative.

```js
{
  on: {
    "": { target: "x", actions: "y" },
    foo: {}
  }
}

// vs

{
  onEntry: { target: "x", actions: "y" }
  on: {
    foo: {}
  }
}
```

The docs will need to be updated, because then `onEntry` and `onExit` will become special transitions and not actions anymore. 

What do you think?

**Comment by davidkpiano** [comment]
Unfortunately this would go against the spec: https://www.w3.org/TR/scxml/#onentry

`<onentry>` can only have executable content as children. 

Also, we don't want to conflate `onEntry` with transient transitions - they're not exactly the same. Consider that a state can have both an `onEntry` action(s) _and_ a transient transition.

**Comment by hnordt** [comment]
@davidkpiano thank you.

Just for curiosity, could you explain the difference between:

```js
{
  on: { "": { actions: "foo" } }
}

// and

{
  onEntry: { actions: "foo" }
}
```

?

**Comment by davidkpiano** [comment]
That code wouldn't work (by definition); it would give you an infinite loop, since it reenters the same state every time and always executes the same null transition.

The best way to think about null events and transient transitions are as **choice pseudostates** - that is, commonly, they're a sort of "fake state" that _decides_ which state the machine should really go to. Here's an example: 

<img src="https://upload.wikimedia.org/wikipedia/en/c/c1/UML_state_machine_Fig2.png" />

From here: https://en.wikipedia.org/wiki/UML_state_machine#/media/File:UML_state_machine_Fig2.png
