### ISSUE TITLE
How to generate my own visualization locally?

### ISSUE THREAD

**Issue by createthis** [davidkpiano/xstate#306]
Hello,

How can I generate my own visualizations locally? I see the beta viz link, but I want to be able to generate these graphs myself, offline.

Thanks

**Comment by davidkpiano** [comment]
The visualizer is open-source: https://github.com/statecharts/xstate-viz

**Comment by pawanmgit** [comment]
https://github.com/statecharts/xstate-viz : is still active ?. I see no commit activity. Do you have a new repo for it now ?

**Comment by Glavin001** [comment]
Really disappointed to see the XState visualizer and inspect are no longer officially maintained by Stately organization. As someone who has loved using XState and therefore (successfully) promoted it to multiple teams I've worked with over these past few years, this now makes me think twice.

I really appreciated XState being able to offer a great local development experience, and any issues I had with implementation or documentation I could always peak under the open-source hood to see why. The visualizer was one of my favorite tools and value points of XState, sad to see it go unsupported.

**Comment by davidkpiano** [comment]
> Really disappointed to see the XState visualizer and inspect are no longer officially maintained by Stately organization. As someone who has loved using XState and therefore (successfully) promoted it to multiple teams I've worked with over these past few years, this now makes me think twice.
> 
> I really appreciated XState being able to offer a great local development experience, and any issues I had with implementation or documentation I could always peak under the open-source hood to see why. The visualizer was one of my favorite tools and value points of XState, sad to see it go unsupported.

I appreciate the feedback. A couple of things to share:

We're working on an open-source machine visualizer - think lightweight, embeddable, visually similar to sketch.systems. It won't be the full canvas editor, but it'll give you a solid way to visualize your machines locally during dev. We want that inspect/visualize workflow to remain accessible to everyone.

The full-featured visual editor is evolving into a more robust product (with self-hosting easily embeddable options), which is why the maintenance model is shifting, but the goal isn't to take away from the OSS experience, it's to make everything sustainable so we can keep investing in the ecosystem.

We'll share more soon. Would love your input as someone who's been championing XState (very appreciative of that).

<img width="1374" height="1314" alt="Image" src="https://github.com/user-attachments/assets/8e1c39d5-cd5c-4518-a898-cab829bc8342" />

**Comment by Rhym** [comment]
@davidkpiano Hello! Was there any update on the following?

> We'll share more soon. Would love your input as someone who's been championing XState (very appreciative of that).

I too have been using XState for the last couple of years, and would like to advocate it on my new team, and being able to locally view the machine logic would be very helpful.

**Comment by davidkpiano** [comment]
@Rhym Yes, not announced publicly yet, but I will be open-sourcing [sketch.stately.ai](https://sketch.stately.ai) soon.

**Comment by Rhym** [comment]
Thanks, @davidkpiano! Looking forward to it.

**Comment by davidkpiano** [comment]
> Thanks, @davidkpiano! Looking forward to it. 

By the way, this is now open source at https://github.com/statelyai/sketch
