### ISSUE TITLE
Restore machine state from localStorage

### ISSUE THREAD

**Issue by ferdinandsalis** [davidkpiano/xstate#31]
I hope its fine to ask about an implementation detail … Would it be possible to restore the machine state from localStorage (e.g. when refreshing the site)? If yes would be simplest way to do it?

**Comment by davidkpiano** [comment]
Yep, just `JSON.serialize` the resulting `State` from a transition and use [the `localStorage` API](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) to `.setItem('state', jsonState)` and `.getItem('state')`.

I'm not going to add this to xstate though, since it's an implementation detail. Cool idea, though! 😄

**Comment by ferdinandsalis** [comment]
Thanks ☺️. Its so easy. I had some wrong mental model in my head about xstate …

**Comment by macs91** [comment]
@davidkpiano I'm having this issue when performing a transition from a deserialized state:

`TypeError: Cannot read property 'transitionStateValue' of undefined`

Here a codesandbox that reproduces the issue:
[![Edit xstate state serialization issue](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vn4ljv6p8y?module=%2Fsrc%2Findex.js)

The **workaround** I've found is to create a new state with `State` constructor using the paramenter retrieved from the deserialized state.
