### ISSUE TITLE
Accept single object instead of multiple args for Machine

### ISSUE THREAD

**Issue by dakom** [davidkpiano/xstate#314]
Basically a duplicate of https://github.com/carloslfu/use-machine/issues/6 (but I hadn't realized at the time it was following the API here)

When creating a machine with initialContext but no "options" arg it requires passing null/undefined, e.g.

`Machine(config, null, initialContext);`

I think it would be a bit nicer if `Machine` instead took an object such that all these are valid:

```
Machine({config});
Machine({config, options});
Machine({config, initialContext});
Machine({config, options, initialContext});
```

**Comment by dakom** [comment]
With this in mind it might make sense to bring the different `options` up a level. In other words:

```
Machine({config, initialContext, actions, services});
Machine({config, initialContext, actions, guards, services, activities});
//etc.
```

**Comment by davidkpiano** [comment]
Unfortunately, this is probably not a good idea, because `actions`, `services`, `guards` are implementation details, that can change depending on how the statechart is consumed.

A good way to think about this is that `config` should be able to be a plain JSON object:

```js
const config = require('./someMachine.json');

                    //  👇 from JSON
const machine = Machine(config, {/* ... */});
```

Also, you can already specify `initialContext` via the `context` property in `config`. You can change this by specifying `context` as the 3rd argument, although I can see that being part of the 2nd argument. If you want that, please open a new issue for that.
