### ISSUE TITLE
Circular transition and effects

### ISSUE THREAD

**Issue by lmatteis** [davidkpiano/xstate#32]
I was wondering about circular transitions and why no "effects" are returned when this happens:

https://github.com/davidkpiano/xstate/blob/master/test/effects.test.ts#L121

I'm thinking there could be a `FetchingData` state, which a transition back to itself when `RETRY` is triggered. Using `onEntry` I could define that I want the data to be refetched, but right now returns empty array when this happens.

Thoughts?

**Comment by dodekeract** [comment]
I think there should be a different hook then. Something like `onReEntry`.

**Comment by davidkpiano** [comment]
It returns no effects because no transition occurred - that is, there's no defined transition for `'NOTHING'` actions, so this is the expected behavior.

Now **self-transitions** are different. I'll add tests to ensure that if a state transitions to itself, it will return its own `onExit`/`onEntry` handlers as effects.

**Comment by lmatteis** [comment]
I'm a bit confused. Why do you call them actions? NOTHING is an event, isn't it? Does xstate even support actions? And the green state seems to have `{ on: NOTHING: ... }`, but again maybe I'm missing something.

**Comment by davidkpiano** [comment]
Hmm, you're right. I've been using the word "action" in the Redux sense of the word, even though in statecharts an action is what I refer to as an "effect" (as in, a side-effect). I think there is an opportunity to clarify this (but please open a separate ticket for that).

**Comment by mogsie** [comment]
So after the rename, the _event_ NOTHING when in the _green_ state, it should _exit_ the green state and then _enter_ it again, triggering both exit and entry actions of _green_:

```js
      green: {
        on: {
          NOTHING: 'green'
        },
        onEntry: 'enter_green',
        onExit: 'exit_green'
      },
```

thus the test should check that green→green has actions `exit_green` and `enter_green`.  Correct?

**Comment by davidkpiano** [comment]
You're correct; SCION also exhibits this behavior. Here's the details:

- If a state has an explicit self-transition (e.g., `NOTHING: 'green'` for `'green'`), then it will exit and enter the state, calling the `onExit` then `onEntry` action(s).
- If a state does not handle an event (e.g., some `FAKE` event), then the state will remain unchanged, and no actions should be executed.
  - The idea of a `sink` state should be considered in the future, but having unhandled events automatically go to a `sink` state should not be done by default, as it would require much more configuration. The fact that no actions are returned in the resulting state should be enough to indicate that the state has not handled the event.

**Comment by mogsie** [comment]
Hi, I sent a tweet but figured it would be better to add the comment here for context / posterity:

For any unhandled events, I think it would be more natural if the transition() function functioned a bit like an identity function, returning the same state instance as before, when the event was _unhandled_.

Given the `green` state above:

```js
state = transition(somestate, 'NOTHING'); // returns a state `exit_green` and `enter_green` (this issue)
state = transition(somestate, 'ABRAKADABRA') // returns `somestate
if (state !=== somestate) {
  // execute exit + entry actions
}
```

Hmm. But I see the problem here, if you don't know this specific nuance, then you might end up executing the same entry/exit actions twice. Hmm.  I see now the wisdom of returning `undefined` when the event was ignored by the state machine.

So indeed, either leave it as undefined, or return a new instance of State with no entry/exit actions.

In my work, I've seen the need for knowing definitively if a state machine actually handled an event or not, because you might want to e.g. `preventDefault` if it _was_ handled, and let the event "do it's thing" if the state machine didn't recognise it.

**Comment by davidkpiano** [comment]
I used to have a "changed" prop (Boolean) on the State object. I can add it back, if it makes things easier.

Then again, preventDefault can be considered an action...

Also it's much less frustrating to always return a state - and I'd like to discuss a "sink" property which will specify what happens on unhandled events, could be useful.

**Comment by mogsie** [comment]
I like to keep preventDefault out of the statechart since it binds it (a bit too close) to the event handling that triggered the signal. You know me, I like to keep things separate. IMHO it belongs closer to the code that passes the event _to_ the state machine, so being able to know "ah, yes, the state machine knew about this click, great, I'll preventDefault it" is a good thing :)
