### ISSUE TITLE
v3 fails to install (postinstall)

### ISSUE THREAD

**Issue by apostolos** [davidkpiano/xstate#34]
Using yarn to install 3.0.0:

```\node_modules\xstate: Command failed.
Exit code: 2
Command: npm run build && npm run build:utils
Arguments:
Directory: ....\node_modules\xstate
Output:
> xstate@3.0.0 build ....\node_modules\xstate
> tsc && webpack -p ./lib/index.js ./dist/xstate.js --config webpack.config.js

error TS2688: Cannot find type definition file for 'mocha'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! xstate@3.0.0 build: `tsc && webpack -p ./lib/index.js ./dist/xstate.js --config webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the xstate@3.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?```

**Comment by davidkpiano** [comment]
Install `xstate@latest`, v3 is not out yet. (I haven't even written documentation 😅 but I intend to for V3).

**Comment by MicheleBertoli** [comment]
Hello @davidkpiano, I would also like to use v3 : )
Do you have any plans to publish the current master (e.g. v2.2)?
I'm interested in `strict` (f6799d3), `effects > actions` (9f60664) and `getSimplePaths` (f1484a5).
Thank you very much!

**Comment by davidkpiano** [comment]
I'd wait for V3 to use getShortestPaths because I've made a lot of improvements on the algorithm so that it also handles parallel machines, and it also has getSimplePaths which returns all simple paths in the connected graph (many more than getShortestPaths). I plan to finish V3 and documentation this weekend! For now you can install it from the @beta tag (or directly from the repo on the v3 branch).

**Comment by MicheleBertoli** [comment]
Sounds perfect, thank you very much @davidkpiano.
`getShortestPaths` + parallel machines = 💣
You are awesome.
