### ISSUE TITLE
assign object vs function syntax typescript support

### ISSUE THREAD

**Issue by RainerAtSpirit** [davidkpiano/xstate#385]
## Bug or feature request?
feature request I guess

## Description:

When using `assign` with the recommend object syntax `ctx` and `event` are inferred as any.

## (Bug) Expected result:

`ctx` and `event` should be inferred with the correct types
function syntax  https://codesandbox.io/s/pmx5j5n2p0 todoMachine.ts line 96

![image](https://user-images.githubusercontent.com/581644/53959432-ed082a80-40e3-11e9-8985-48d767f2b970.png)

![image](https://user-images.githubusercontent.com/581644/53959427-e679b300-40e3-11e9-8f66-2787a29236c6.png)

## (Bug) Actual result:

for incorrect types using object syntax  https://codesandbox.io/s/pmx5j5n2p0 todoMachine.ts line 93
![image](https://user-images.githubusercontent.com/581644/53959445-f2657500-40e3-11e9-8cf8-6b952d54ac80.png)

## (Bug) Potential fix:

-

**Required!** If you found a bug and can consistently reproduce it, please take a minute to think about what the potential fix might be.
Even if the fix is incorrect, this can help diagnose and find the solution to the issue as quickly as possible.

I also strongly encourage you to [create a pull request](https://github.com/davidkpiano/xstate/pulls) if you are confident in the potential fix.

## (Feature) Potential implementation:

**Required!** If you would like to see a feature or enhancement make its way to xstate, please describe:
- What the API would look like
- If this is a breaking change
- If this is part of the existing [SCXML specification](https://www.w3.org/TR/scxml/)

## Link to reproduction or proof-of-concept:

You can use [CodePen](codepen.io) or [Code Sandbox](codesandbox.io) to create a reproduction/POC.

**Comment by ksaldana1** [comment]
With [propagated generics in higher order functions](https://github.com/Microsoft/TypeScript/pull/30215) released in TypeScript 3.4, this assign object syntax now infers correctly.

<img width="683" alt="Screen Shot 2019-04-13 at 8 23 13 AM" src="https://user-images.githubusercontent.com/12038627/56081007-96b69780-5dc5-11e9-922c-9d4c28174f75.png">

@davidkpiano I believe this issue can now be closed.

**Comment by davidkpiano** [comment]
@ksaldana1 Does that also infer the `ctx` correctly?

**Comment by ksaldana1** [comment]
@davidkpiano It does, yes. I am having trouble getting this inference to replicate on Codesandbox, so might want to hold off before someone else can confirm. I'm not sure if it's a limitation in the language server on codesandbox or something else. I upgraded recently at work and pulled out a bunch of generics because of the TS change. 
<img width="683" alt="Screen Shot 2019-04-13 at 9 59 52 AM" src="https://user-images.githubusercontent.com/12038627/56082199-fff0d780-5dd2-11e9-83fd-988865f97a0b.png">
<img width="602" alt="Screen Shot 2019-04-13 at 10 03 27 AM" src="https://user-images.githubusercontent.com/12038627/56082222-6c6bd680-5dd3-11e9-999e-3bfc4b3e4e21.png">

**Comment by RainerAtSpirit** [comment]
@ksaldana1 : thanks for the update. 
@davidkpiano I can confirm this is working in VS Code with TS 3.4.3.
![image](https://user-images.githubusercontent.com/581644/56090849-eb324380-5ea7-11e9-829a-271d2b196306.png)
