### ISSUE TITLE
Parallel machine transition resetting sibling states

### ISSUE THREAD

**Issue by bradwoods** [davidkpiano/xstate#400]
## Bug

When a transition is fired for a nested parallel machine, it changes the targeted state as expected but changes all sibling states to their initial value.

[Code Sandbox](https://codesandbox.io/s/wk8oxpqrkw)

**Comment by hnordt** [comment]
It's intentional, as `dog` is a parallel state node you can think of `GO_WALKING: ".dog.walking"` as transitioning the machine to `{  pets: { dog: "walking", cat: undefined } }`. `undefined` will get "converted" to the state node's initialState.

You can use multiple targets when working with parallel states (it's not live yet):

https://github.com/davidkpiano/xstate/commit/544dfb3246340c05a7643123035121f5ba3c9c0d

**Comment by davidkpiano** [comment]
You're right, but I think this should be addressed for use-cases like:

```js
{
  on: {
    GO_WALKING: {
      target: ['.dog.walking', '.cat.walking'],
      internal: true
    }
  }
}
```

But you can also handle each transition within the `.dog` or `.cat` states themselves as an idiomatic workaround.

**Comment by hnordt** [comment]
@davidkpiano I think `{ target: ['.dog.walking', '.cat.walking'], internal: true }` is a bit redundant, the machine already knows `.someChildState` is internal, I'd say the machine should know what to do when you omit `interval`: `{ target: ['.dog.walking', '.cat.walking'] }`.

**Comment by davidkpiano** [comment]
Closing as this is addressed.
