### ISSUE TITLE
[Feature] Batched Events

### ISSUE THREAD

**Issue by davidkpiano** [davidkpiano/xstate#409]
## Bug or feature request?
Feature

## Description:
This feature will allow interpreted machines (services) to execute multiple events at once:

```js
const events = [
  // can be strings
  'EVENT',
  'EVENT',
  'OTHER_EVENT',
  // and/or objects
  { type: 'EVENT', payload: [] },
  { type: 'OTHER_EVENT' }
];

// .send(...) can accept a single event or multiple events
service.send(events);
```

The differences between this and manually sending multiple events (e.g., in a for-loop) are:

- The `.onTransition(...)` and other listeners will only be called **once** - when all events are done processing. 
- The state that results from all the events will aggregate the actions of the intermediate states.

This is great for performance, simulation, testing, rehydration, etc. because you can prevent potentially expensive updates from being made by only responding to state changes after all batched events are processed, instead of every single event.

No breaking changes.

**Comment by johnyanarella** [comment]
Sounds worthwhile, to avoid the extra notifications for the scenarios you mentioned.

I assume:

* activities would not be started for intermediate steps, being zero-time transitions; and
* intermediate `invoke`-ed services would also be skipped, with the expectation that the corresponding `done.invoke.someId` (or even `error.execution` for event sourcing reconstruction) events would be present instead?

**Comment by davidkpiano** [comment]
Right - this will be the natural outcome anyway, since some of the aggregated actions at the last "accumulated state" will cancel each other out; e.g.:

```js
// assume this is from a batch transition
// (illustrative purposes only)
state.actions;
// { type: 'xstate.start', activity: 'A' }
// ...
// { type: 'xstate.start', activity: 'B' }
// ...
// { type: 'xstate.stop', activity: 'A' }

// activity A won't be started
state.activities.A; // => false;

// ... but activity B will!
state.activites.B; // => truthy
```

**Comment by johnyanarella** [comment]
Hmm. When you refer to "aggregated actions", do you mean that:

* conceptually - the resulting state will reflect the result of all of the intermediate actions as executed during those intermediate transitions; or
* literally - the resulting state's `actions` aggregates all the deferred actions triggered by the intermediate transitions.

(I originally assumed you meant the first, but I'm less certain now.)

or in pseudocode:

```js
events.forEach(event => {
    currentState = machine.transition(currentState, event)
     performActions(currentState, currentState.actions)
    // ...
})
notifyTransition(currentState)
performActions(currentState, currentState.actions)
```

vs

```js
let aggregatedActions = []
events.forEach(event => {
    currentState = machine.transition(currentState, event)
    aggregatedActions = aggregatedActions.concat(currentState.actions)
    // ...
})
currentState.actions = aggregatedActions
notifyTransition(currentState)
performActions(currentState, aggregatedActions)
```

The second approach is problematic for custom actions and services, as they receive `(event, context)` as their parameters when executed. That event should still be the one from the transition that triggered the action (including its payload), rather than the final event.

Additionally, invoking callbacks (or machines) becomes problematic, since those can send events (potentially immediately on execution before being stopped), which could now occur out-of-order and outside their original state relative to individually sending the same events.

**Comment by johnyanarella** [comment]
I take your point that skipping activities / invocation is an unnecessary optimization and a dangerous assumption - since the subsequent events might not necessarily transition out of the state that started the activity or invoked a Promise/callback/machine.

So, that whole "assume events can come from anywhere at any time" rule comes up again.

If I'm testing or rehydrating and want to transition past a state that would normally invoke a Promise, I could send along `done.invoke.someId` to simulate resolution (or `error.execution` to simulate rejection) in the batched events to progress past that invocation, right? If I transition away, the original Promise will be cancelled.

(Side note: worth investigating if the service cancels the original Promise if a `done.invoke.someId`/`error.execution` comes in externally, rather than from the Promise. Otherwise, could there be an issue if `onDone` doesn't transition away, and the Promise later resolves or rejects....)

**Comment by davidkpiano** [comment]
Let's open a separate issue if any problems arise with batched events with regard to activities/services.
