### ISSUE TITLE
Transition trigger on nested event?

### ISSUE THREAD

**Issue by tkaragianes** [davidkpiano/xstate#41]
First off, thanks for the library and excellent CSS-Tricks articles. They've really improved how I structure my state management. I'm restructuring a site with this new approach, but I'm running into unexpected behavior with nested states. My understanding is that a state should only transition to it's next state on events defined in it's on object. Using the Light Machine example, the "green" state only transitions in response to "TIMER" and "POWER_OUTAGE" events.
```
lightMachine.transition("green", "TIMER") // "yellow"
lightMachine.transition("green", "POWER_OUTAGE") // "red"
```
However, as illustrated in [this Codepen](https://codepen.io/brainbow/pen/wpypYZ), it seems to also fire a transition on the "PED_COUNTDOWN" event. I see that a recent breaking change results in transition always returning a state. Why? I would expect that any event not specified in the on object of a state or it's parent states should be ignored, and that no state would be returned from a transition if no state transition occurred.
```
lightMachine.transition("green", "BROKEN") // "Error: Machine 'light' does not accept event "BROKEN"
lightMachine.transition("green", "PED_COUNTDOWN") // "green", expect no response or error
```
For context, the reason I'm curious is for animated page navigation. In order to properly make page transitions work, you need to keep a history of states navigated to so that popstate can be implemented correctly. Barba.js has some problems doing this consistently and correctly, which is why xstate seems more promising.

**Comment by davidkpiano** [comment]
> I see that a recent breaking change results in transition always returning a state. Why?

Two reasons:
1. In practice, (I dogfood `xstate` in lots of places) it was pretty unpragmatic and more complex to implement a `.transition(...)` function that could either return a `State` or `undefined`, because you had to first check if the state was undefined before getting its `.value`.
2. With the addition of actions (`onEntry`, `onExit`, `actions` in transitions), any side-effects you'd need to execute were declared on the statechart.

With the second point, you could then just check if `nextState.actions.length` was empty. If so, it means that there are no side-effects to execute. `.actions` is empty if you're transitioning from an unhandled event (such as `BROKEN`).

However, it might make some sense to add a `changed` property to the `State` object, indicating whether the previous state handled the event and actually did transition, instead of staying still. Would that solve your problem? 

All you'd have to do (when the feature is in) is check `state.changed` (boolean).

**Comment by tkaragianes** [comment]
Makes sense. I'm not sure the changed property is necessary; I could handle the checking by comparing to the last history state. There may be some value in terms of overall flexibility, but I don't know if it's worth it. I'm still playing around with implementing the PJAX functionality and element / layout animations via the actions object. I'll let you know if the changed property would help. Thanks again!
