### ISSUE TITLE
Invoking Multiple services error

### ISSUE THREAD

**Issue by EmirGluhbegovic** [davidkpiano/xstate#470]
## Bug or feature request?
Bug

Replicated here: https://codesandbox.io/embed/heuristic-mountain-1kh0n

_Please note I made the login a random boolean, so the error path is triggered when it randoms false_

## Description:
I am invoking 2 services in a state. The first service is a promise and the second one is a machine. I need when the onError action hits from the promise service to send an action to the child service. At the moment I get back an error when I call the child machine action in the onError action. 

## (Bug) Expected result:
I would expect that the child machine action would be called

## (Bug) Actual result:
`index.js:1375 Missing onError handler and/or unhandled exception/promise rejection for invocation 'login'. Original error: '[object Object]'.  Current error is 'Error: Unable to send event to child 'notification' from service 'authentication'.'. Stacktrace was 'Error: Unable to send event to child 'notification' from service 'authentication'.`

## (Bug) Potential fix:

**Required!** If you found a bug and can consistently reproduce it, please take a minute to think about what the potential fix might be.

In the attached code sandbox I commented out line 97. To fix the issue you must remove the "reportError" action from line 92 and add back line 97. The reason this is not the ideal solution is that 97 will always be triggered and I will have to add logic to tell whether it is an error or not while if it was triggered on line 92, it will only be triggered on an error.

## Link to reproduction or proof-of-concept:

Replicated here: https://codesandbox.io/embed/heuristic-mountain-1kh0n

**Comment by davidkpiano** [comment]
There is basically a "race condition" here. With the given machine config, you are doing two things at the same time:

- Stopping the `notification` service
- Sending an event to the `notification` service

This should be a ~code smell~ red flag. Why does the `notification` service need to be stopped?

Personally, I'd refactor this so that the `notification` service is invoked throughout the lifetime of the machine:

```js
const authMachine = Machine({
  // ...
  invoke: {
    src: notificationMachine,
    id: 'notification'
  },
  states: {
    // ...
  }
  // ...
});
```

See here for a working example: https://codesandbox.io/s/vigilant-torvalds-u4pvm
