### ISSUE TITLE
Targeting nested state node using id fails

### ISSUE THREAD

**Issue by GU5TAF** [davidkpiano/xstate#475]
## Bug or feature request?
Bug
## Description:
Targeting a nested state node using id doesn't work.
`bar.qux.quux` works whereas `#bar.qux.quux` does not.

## (Bug) Expected result:
Should work

## (Bug) Actual result:
Substate '#bar' does not exist on '(machine)'

## Link to reproduction or proof-of-concept:
[Link to reproduction](https://codesandbox.io/embed/targeting-nested-state-on-parrallel-node-iurrf)

**Comment by davidkpiano** [comment]
Right now this is working as expected, because you're looking for a state with ID `"bar.qux.quux"`, and _not_ a state with ID `"bar"` with child states `"qux"` and `"quux"`.

Maybe there should be a resolution algorithm that first checks the entire `"#<ID>"` string, and then breaks apart the `<ID>` via the `'.'` delimiter and finds nested states instead? Would that add too much complexity? cc. @mogsie

**Comment by GU5TAF** [comment]
Gotcha, I've updated any mentions of type parallel as it wasn't of importance.
I'd appreciate a resolution algorithm, it'd feel consistent with how no id'd targets work currently.

**Comment by davidkpiano** [comment]
Actually, I realized your example does work as expected, there's just a typo:

```diff
const brokenMachine = Machine({
  initial: "foo",
  on: {
    ACTION: "#bar.qux.quux"
  },
  states: {
    foo: {
-     id: "#foo"
+     id: "foo"
    },
    bar: {
-     id: "#bar",
+     id: "bar",
      states: {
        baz: {},
        qux: {
          states: {
            quux: {}
          }
        }
      }
    }
  }
});
```

**Comment by GU5TAF** [comment]
Oh, well that's embarrassing... my bad 🙏 
Thanks for taking the time to look into it!
