### ISSUE TITLE
Bug: `interpreter.send` crashes when called with a circular structure

### ISSUE THREAD

**Issue by macbem** [davidkpiano/xstate#482]
[Related to this line](https://github.com/davidkpiano/xstate/blob/master/src/interpreter.ts#L454).

When you pass a circular structure to this function in non-production envs, `interpreter.send` tries to log a warning using `JSON.stringify`, which then throws.

Expected result: it should not throw :sweat_smile: 
Recommended solutions (pick one or both):
- make warnings optional and configurable (not depending on env)
- wrap a `try / catch` around the `JSON.stringify` call and report that you failed to stringify the object

This is a bit of a problem for me since it's a popular pattern in MobX to use circular structures for data stores ([it's even recommended in the official docs](https://mobx.js.org/best/store.html#combining-multiple-stores)).

I use this to provide an "outside world" state to the state machine via guards, e.g. `interpreter.send({ type: 'NEXT', contextService: /* class with circular refs that has getters to the global store */ })`.

Before I get criticized for not using state machines properly: this is an approach I picked knowing all of its drawbacks - I just needed a declarative way of defining state transitions of a really small part of my app and figured that this is the easiest / most effective way to do it. I'll understand if you'll decide not to accept my bug report because of this.

Let's discuss this and I'll be glad to send a PR once we reach consensus.

**Comment by davidkpiano** [comment]
> Before I get criticized for not using state machines properly

Nah this is fine - ideally, the `context` of a machine should be any (ideally serializable) data structure, not just POJOs. Are MobX's data structures serializable?

**Comment by macbem** [comment]
Yes, they are - `JSON.stringify` accepts a second argument that allows you to handle circular references. This is also one of the approaches we could take to solve this.

Just to clarify - it's not `context` that's the problem - it's the event passed to `interpreter.send()`. I don't use context.

**Comment by macbem** [comment]
Sure, I'll try to set up a reproducible example for you.

**Comment by macbem** [comment]
Here you go - sample code that's triggering the issue, with a setup similar to mine, just without MobX decorators [https://stackblitz.com/edit/typescript-hxgu7x](https://stackblitz.com/edit/typescript-hxgu7x).

The reason why I supply the context via guards is because xstate context is supposed to be mutated only internally.

As a response to your comment - even if the best practice is that events are JSON-serializable, in my opinion, xstate shouldn't throw when they aren't if there aren't any specific technical reasons for this.

**Comment by davidkpiano** [comment]
This is more of a design issue - events should definitely be serializable, and only include what they need to include.

Your `{ type: 'NEXT', ... }` event can be simplified to:

```js
{
  type: 'NEXT',
  isAuthenticated: true // contextService.currentUser.isAuthenticated, etc.
}
```

You might see the obvious problem with that: it's too easy to fake/mistakenly send `{ ... isAuthenticated: true }` even if the user isn't authenticated, and this problem extends to sending the entire service; I can fake that `contextService` with an authenticated user, too.

-------

What's better is to include the user state in context:

```js
{
  // ...
  context: {
    user: contextService.currentUser, // etc.
  }
}
```

And use some sort of observer pattern:

```js
// pseudo-code
contextService.onUpdateUser(updatedUser => {
  myService.send('USER.UPDATE', { data: updatedUser });
}

// ...

{
  on: {
    'USER.UPDATE': assign({ user: (_, e) => e.data })
  }
}
```

This gives you an explicit data flow, and also allows you to separate responsibilities in a flexible way (imagine if user updates came from polling an API endpoint instead of a local  `contextService`, or if the `contextService` implementation changed).

With the above, your event becomes simple and serializable:

```js
{
  on: {
    NEXT: {
      target: 'complete',
      cond: ctx => ctx.user.isAuthenticated
    }
  }
}

// ...

myService.send({ type: 'NEXT' });
```

Let me know if you have any more questions on this 😄
