### ISSUE TITLE
reference sender/self of an event

### ISSUE THREAD

**Issue by VinSpee** [davidkpiano/xstate#486]
## reference sender/self of an event

Hi! We discussed this some on [gitter](https://gitter.im/statecharts/statecharts?at=5cfb0c91ff3f016baac2b4c0). 

potential API:

```js
// child
{
  actions: sendParent('PONG')
}

// parent
{
  on: {
    PONG: {
      // TENTATIVE API (sender)
      actions: send('PING', { to: (ctx, e, { sender }) => sender })
    }
  }
}
```

spec compatible?

> This is SCXML compatible and corresponds to the sendid on the _event meta-object

and even a potential abstraction / api addition:

```js
// parent
{
  on: {
    // same as send(...) to sender
    PONG: { actions: respond('PING') }
  }
}
```

**Comment by davidkpiano** [comment]
> I believe it (sendId) should be set on the event object itself and not provided on the new meta object provided as argument to the actions.

This would be a breaking change, and a bit of an inconvenience for development. At least in terms of the arguments passed to `(ctx, e, ...) => ...` functions, it's easier to have:

```js
event === {
  // the raw event
}
```

Rather than:
```js
event === {
  sendId: ...,
  // other SCXML props
  data: {
    // the raw event
  }
}
```

We can revisit this for version 5, but the safest thing to do for now is have the "SCXML event" as a "meta object".

**Comment by Andarist** [comment]
> We can revisit this for version 5, but the safest thing to do for now is have the "SCXML event" as a "meta object".

Would SCXML event be user~ event extended with SCXML-metadata or would it contain only SCXML-metadata?

**Comment by davidkpiano** [comment]
Yes, see here: https://www.w3.org/TR/scxml/#InternalStructureofEvents

```
{
  name: ...
  type: ...
  sendid: ...
  origin: ...
  origintype: ...
  invokeid: ...
  data: ...
}
```

Implementation has started on this (see the `SCXML.Event` type). An SCXML processor would make this available on `_event`, which is why I would include it in the signatures as `(context, event, { _event })` (I didn't add that underscore myself, I promise!)

Also, note that `name` is the "event type" and `type` refers to `"platform"` or `"internal"` or `"external"`.
