### ISSUE TITLE
Dynamic meta support

### ISSUE THREAD

**Issue by hnordt** [davidkpiano/xstate#493]
I would like to make a PR to add support for dynamic `meta` values, just like the `data` property:

```js
// data property

let stateNode = {
  reveal: {
    type: 'final',
    data: {
      secret: (context, event) => context.secret
    }
  }
}

// dynamic meta

let machine = {
  id: "telecom"
  states: {
    idle: {
      on: {
        RECEIVE_CALL: "incoming"
      }
    },
    incoming: {
      entry: "setCaller",
      on: {
        HANG_UP: "idle"
      },
      meta: {
        callerName: context => context.caller.name
      }
    }
  }
}
```

**Why it would be useful?**

By reading from `currentState.meta` the UI stays decoupled from the machine structure. I can refactor both my state and extended state (context) shape and the UI won't break.

`meta` can also serve as a way to implement contextual selectors, so I can replace things like:

```js
let callerName = state.matches("incoming") && state.context.caller.name
```

With:

```js
// Here I don't need to check for `state.matches("incoming")` because
// `meta.callerName` will be only available when the machine is in the incoming state
let callerName = state.meta.callerName
```

One more thing, `meta` can also serve as an alternative to using `activities` as viewflags. See related discussion: https://spectrum.chat/statecharts/general/coupling-between-view-and-statechart~5ad2e6bb-a33d-48ac-baaa-a69c1406456b?m=MTU2MDQ3MjY2Mzk3MQ==

@davidkpiano if you agree, I can make a PR.

**Comment by hnordt** [comment]
cc @mogsie

**Comment by davidkpiano** [comment]
This looks like a decent idea, but a few thoughts:

- Wouldn't this be equivalent to setting context? And the benefit of having this in `assign()` calls is that it would only be computed when those assign calls are made, instead of every time the state changes. In your example, `meta.callerName(...)` would be called multiple times, even if the value doesn't change.

- Comparing to `state.matches` approach, this falls apart if you have a "meta" value that's dependent on more than one state. For instance, how would you model app logic that says "The caller name should be prepended with `(wifi)` if wifi is on"? You can't do it with `meta` alone (unless you want that view logic in two separate places), but:

```js
let callerName = state.matches({ connection: 'wifi', call: 'incoming' })
  && `(wifi) ${state.context.callerName}`
```

- Not sure how this would fit in the SCXML spec. The original intention is that `meta` properties referred to plain (arbitrary) XML elements.

- The `meta` property is not intended for computed state; that seems implementation-specific and should live _outside_ the statechart, and inside whatever is interpreting the statechart.

- This can easily be implemented in user-land, without the need for baking it into XState:

```js
const callerName = state.meta.callerName(state.context);
```

Or you can iterate through all the values of `state.meta` and call the function with `state.context` (if the meta value is a function), if you want. Exercise left to reader.

**Comment by hnordt** [comment]
Those are good points. I agree with you, by having dynamic `meta` we could introduce additional complexity for no benefit.
