### ISSUE TITLE
Thoughts on Features

### ISSUE THREAD

**Issue by jmatsushita** [davidkpiano/xstate#5]
Hi there,

Per your comment in #3 I'll share some feature related thoughts here in a "meta-issue" fashion.

It would be good to have a mode (`debug`?) where transition failure returns more than false and maybe a more classic node callback style `(err, result)` pair with a detailed error about what caused the transition failure (source state doesn't exist, target state doesn't exist, event not recognised,...).

Better error messages? A missing state now generates `TypeError: transition.targetState.initialStates is not a function`.

Would be good to document your non-documented exports (`stateReducer`, `mapState`,...) and give some short examples (probably reusing the green, yellow, red example). I'm not sure how I would use `mapOnEntry` and `mapOnExit` for instance. It's great that you have curried versions of these functions and giving some example of that might help share some functional goodness :) 

I'm kicking the tires for an event sourcing application, so I found myself needing a fold time function, i.e. left monadic fold over a list of events/actions, to rebuild the current state. Maybe another candidate for a utility function? ( ```// state -> [ event ] -> state```)

Because of this type of application, performance will potentially matter, so it might be good to have some tests which generate large event sequences and help check that new features don't introduce to much performance penalties.

Maybe more longterm, it might be good to follow the fantasy-land spec and provide functor and monad instances?

Thanks a ton for the lib!

Jun

**Comment by davidkpiano** [comment]
> Maybe more longterm, it might be good to follow the fantasy-land spec and provide functor and monad instances?

I very much want to do this - which is why I want to 1) rewrite this library and 2) get more accustomed to the fantasy-land spec and functional programming as a whole 😄 

My overall goal with this library (or the new one I create) is to have a purely functional and declarative way of expressing statecharts. All existing libraries I've seen fail to do this in a pure, functional way - they all seem to be imperative (e.g., calling `trafficLight.signal()` would set `trafficLight.state == 'green'` or `'yellow'` something like that).

**Comment by jmatsushita** [comment]
Yup, I searched and this is also as far as I know the only declarative and stateless state machine implementation in the nodejs ecosystem. 👍

**Comment by davidkpiano** [comment]
Closing due to V3 being released!
