### ISSUE TITLE
Promise rejection issue in React Native

### ISSUE THREAD

**Issue by jonlaing** [davidkpiano/xstate#511]
## Bug or feature request?

Bug in React Native, actually... sort of...

## Description:

I was getting an issue when a promise rejected, and the error I got was related to React Native's own polyfill of `Object.assign`. It fails on `hasOwnProperty`. I'm not sure if this is still an issue in the latest React Native, but I'm using expo so I'm a couple versions behind.

The offending code in RN is here: https://github.com/expo/react-native/blob/exp-latest/Libraries/polyfills/Object.es6.js#L54

The error I get is: "One of the sources for assign has an enumerable key on the prototype chain. Are you trying to assign a prototype property? We don't allow it, as this is an edge case that we do not support. This error is a performance optimization and not spec compliant."

For the record, the key it's breaking on is `inert` on a state object. Not sure what that's used for, but that's the one it doesn't like. This all takes place in the `resolveState` function.

I think this is related to the new spawning behavior in 4.6.x. I downgraded to 4.5.0, as I wasn't using the actor model stuff anyway and that fixed the issue for me. I don't really expect this library to address the weirdness in React Native, but I wanted to leave this comment here for posterity. I'm not even sure if it could be fixed from this end without breaking something else.

Maybe we can put it in a troubleshooting doc for any other poor souls that run into this?

**Comment by davidkpiano** [comment]
I'd accept a PR to fix this - seems like a simple fix.

**Comment by Andarist** [comment]
@davidkpiano this might actually not be that easy to fix right now, for some reason (I guess it's historical - from the times when spec was not finalized or smth) TypeScript makes class getters enumerable, which is a non spec compliant behaviour. It's reported to TS team and the issue stays opened for few years right now. 

A quick test in latest Chrome:
```js
class Foo {
  instanceProp = 'bar'
  
  get getter() {
    return 42;
  }
}

var test = new Foo()
for (var key in test) console.log({ key })
```
yields expected result of only `"instanceProp"` being logged. However TS-compiled output looks like this:
```js
"use strict";
var Foo = /** @class */ (function () {
    function Foo() {
        this.instanceProp = 'bar';
    }
    Object.defineProperty(Foo.prototype, "getter", {
        get: function () {
            return 42;
        },
        enumerable: true,
        configurable: true
    });
    return Foo;
}());
```
and fails with both keys being logged.

Due to heavy getters usage in XState codebase the fix for this is certainly not a one-liner change. If you rely on those getters being enumerable then a spec-compliant path forward has to be figured out.

**Comment by davidkpiano** [comment]
I think the overall fix would be to get rid of the getters.
