### ISSUE TITLE
Can a substate transition to a sibling of its parent state?

### ISSUE THREAD

**Issue by lmatteis** [davidkpiano/xstate#52]
Hey @davidkpiano,

Was simply wondering if this is even possible using the Statecharts formalism:

```
states: {
  foo: {
    states: { 
      fooSub: { on: { EVENT: 'bar' } }, // when EVENT happens, go to the parent state 'bar'
    }
  },
  bar: {...}
}
```

Thanks,
Luca

**Comment by davidkpiano** [comment]
Given the desire to keep the dot notation (per #53, unless there are strong objections to it, but hopefully I explained the design decision well enough), what do you think a good API would look like?

The important thing is that the keys should be _relative_ to the current state. This is what will allow for full flexibility and composability of statecharts defined in `xstate`.

I know this reads very much like a DSL, but what about something like:

```js
{
  foo: {
    states: {
      sub: {
        // relative to parent, go to 'bar'
        on: { EVENT: '^bar' }
      },
    }
  },
  bar: {}
}
```

This will make the hierarchy explicit (go up one level and then find the sibling `'bar'` state). What do you think?

**Comment by davidkpiano** [comment]
Another option is to do some smart path resolving - that is, when you specify a target state, it will:

1. attempt to resolve it to a relative state path
2. if that fails, attempt to resolve it as an absolute state path to the machine (highest parent)

So for the above:
```
{
  foo: {
    states: {
      sub: {
        on: { EVENT: 'bar' } // resolves to 'foo.bar'
      },
      bar: {}
    }
  },
  bar: {}
}
```

```
{
  foo: {
    states: {
      sub: {
        on: { EVENT: 'bar' } // resolves to 'bar'
      }
    }
  },
  bar: {}
}
```

**Comment by lmatteis** [comment]
That would be cool indeed.

**Comment by davidkpiano** [comment]
Cool, @mogsie @michelebertoli can I get some 👍 and/or 👎 for the above proposed absolute/relative state name resolution? It's deterministic because it will always try relative, then absolute, otherwise error.

However, there might be some value in the `"^bar"` proposal, since it allows more reuse of statecharts. The resolution above would require you to know the entire absolute path of the state.

**Comment by mogsie** [comment]
Seeing as I always saw state names as a global namespace (like SCXML) I just assumed that you could transition the way @lmatteis tried.

Having too much magic makes it harder to make e.g. visualizations that don't also implement the same rules for resolution.

The relative → absolute → error resolution might seem good on a small statechart like this, but is it really intuitive if e.g. you can use it on states and substates, but not siblings' substates?

```js
{
  foo: {
    states: {
      sub: {
        on: { EVENT: 'bar' } // resolves to error?
      },
      one: { states: { bar: {} } }  // 'one.bar' points here
    }
  },
  one: { states: { bar: {} } }  // '^one.bar' resolves here 
  two: { states: { bar: {} } }  // 'two.bar' resolves here
}
```

Or would that be completely out-of-scope?  How wold one target /one/bar

I do see value in how SCXML has declared that state ids must be unique to the whole statechart, since it sidesteps the whole discussion.  But I do see value in having some way of resolving state names when "local".

**Comment by davidkpiano** [comment]
> I do see value in how SCXML has declared that state ids must be unique to the whole statechart, since it sidesteps the whole discussion.

Me too. It's important to note that, even though the state keys are relative, every state naturally has a unique ID; e.g., there is only one `"one.bar"`.

I agree though, the implicit resolution would mean that `bar: {}` might have a resolution in a completely different context from a `bar: {}` at another place, and it's not obvious from looking at the graph. An explicit `"^one.bar"` would mitigate that problem.

So then another option is this:
- `"foo.bar"` will only ever resolve to a relative state
- `"^foo.bar"` is also a relative state, but relative to the parent
- `"#one.two.foo.bar"` is an absolute state, "relative" to the machine. This would be more in line with how SCXML requires unique state IDs specified for transitions, with the addition of `"#"`.

**Comment by lmatteis** [comment]
Definitely like the `^` and `#` syntax. Maybe there's a standard for this stuff (when navigating a tree)? 

Anyway, I've noticed also, when building really complex statecharts, that going from a sub state to a parent state can sometimes be a sign of code-smell (or statechart-smell 😄). In fact, just today, since I couldn't transition to a parent state (as xstate doesn't implement it), it forced me to redesign part of it as a parallel state, which made everything much cleaner.

Anyway, certain edge-cases might need it and I like the options discussed so far!

**Comment by mogsie** [comment]
@lmatteis There is such a thing as [JSON Pointer](https://tools.ietf.org/html/rfc6901) which specifies how to drill down into subelements, much like a file system.  It does not specify "../" for parent looking, but it is not such a stretch considering a "hierarchy" of names, to use normal path semantics.  There are even system libraries to resolve relative paths.

@davidkpiano The phrase "_"foo.bar" will only ever resolve to a relative state_" — you need to clarify: it will resolve to a sibling state, right?  I.e. I can have a state "A" that has a transition to its sibling "B" (the most common case, transitions between states _at the same level_).  Will it at all find any child states of itself?

```
{
  foo: {
    on: { EVENT: 'bar1' }, // resolves to 'foo.bar1' ?
    on: { EVENT: 'bar2' }, // resolves to 'bar2' ?
    states: {
      bar1: {}
    }
  },
  bar2: {}
}
```

**Comment by lmatteis** [comment]
Ah! I like the `../` so you can N levels upwards like `../../Images`. That would mean that substates could be accessed as `./Images/Foo/Bar` instead of `Images.Foo.Bar`?

**Comment by davidkpiano** [comment]
> it will resolve to a sibling state, right?

Correct, sorry for the lack of clarification.

> Would that mean that substates could be accessed as ./Images/Foo/Bar instead of Images.Foo.Bar?

One difference (relevant to @mogsie's clarification) is that whereas `Images.Foo.Bar` refers to `(sibling).(cousin).(grandcousin)`, `./Images/Foo/Bar` refers to `./(child)/(grandchild)/(great-grandchild)`, and it's not straightforward to reference a "sibling" in that directory path notation.

I'd like to be able to allow the developer to specify the `STATE_DELIMITER` though:

```js
const machine = Machine({ ... }, {
  delimiter: '/', // default: '.'
  strict: true,
  // ... other options
});
```

That way, you can represent relative states as `{ EVENT: 'foo/bar' }` instead of `'foo.bar'` if you desire. I don't know how useful that is though.

If there's anything I've learned from state machines, the more possible configurations you can have, the (exponentially) more possible states you will have.

**Comment by mogsie** [comment]
Mm. Making the state delimiter configurable makes state machines harder for me to read, if you use an odd delimiter (like `#` or `^`).

Anyhow, *most* transitions in state machines I have authored are between sibling states, and this is in general good statechart design (I believe) since it means you can easily hide the internals of a state and still see how it "behaves" by and large.  It's of course not avoidable, but making the common case easiest makes sense.  so "foo" always targeting sibling states is fine with me.  I.e. "foo" wouldn't consider child states or parent's sibling states at all, you'd _have_ to use some form of modifier.

Let's say I'm in the "foo" state:

| Target what | How? | What happens? |
| --- | --- | --- | 
| sibling state | `bar` | ... |
| child state | `foo.bar` (repeating my state is a bit ugly, yes) | "foo" is a reference to "itself" and ".bar" is _drilling down_ into foo.
| parent sibling state | `^bar` | ^ indicates to go "up" a level to look for siblings |
| sibling's substate | `mysibling.bar` | mysibling is a sibling of the state in question, so go there and "down" to "bar". |

I think this is succinct for, and keeps it simple for the common case of targeting other states at the same level.  I guess this is close to what @davidkpiano was suggesting all along.

**Comment by davidkpiano** [comment]
Yep, makes sense. Also, I wouldn't worry about the redundancy of navigating to a child state because that would never occur - if a parent state has child states, it has an `initial` state (unless its child states are orthogonal), so it would be in its initial child state already - and then the other syntaxes apply.

**Comment by mogsie** [comment]
Wait, what do you mean by "and then the other syntaxes apply"?  Concrete example:

```
{
  A: {
    on: { ONE: 'B',
            TWO: 'A.B' }
    initial: A
    states: {
      A: {}
      B: {}
    }
  },
  B: {}
}
```
This slightly confusing statechart has two states A and B, while A has two substates A.A and A.B.  The event ONE would unambiguously take it to state B (the root state B), while the event TWO would target the A.B state.  Moreover, I don't think xstate has the notion of internal or external events, so it would perhaps _exit_ the root A state and enter A, then A.B (not the initial A.A).

Is this right?

**Comment by davidkpiano** [comment]
> Moreover, I don't think xstate has the notion of internal or external events

This is something I want to add soon - and it will probably come as a result of #43.

For the example above, to exemplify what I was saying:
- Entering `A` necessarily enters `A.A`, so the current state is `A.A`
  - Note: it's impossible to be in state `A` without being in one of `A`'s substates, per statechart semantics. A parent state with substates cannot be a leaf node state.
- On `ONE` from `A.A`, the event is not handled from `A.A`, so it transitions from the parent to `B`
- On `TWO` from `A.A`, the event also isn't handled, so (if we are deciding against relative/absolute state resolution steps in order to mitigate ambiguity), this will throw an ⚠️ error ⚠️  since `A.A.B` does not exist.

So if you want to transition to `A.B`, the configuration (given your table) should look like:
```js
{
  A: {
    on: {
      ONE: 'B', // A.B
      TWO: '^B', // B
    },
    // ...
  },
  B: {}
}
```

**Comment by mogsie** [comment]
I agree that when it Enters A, it also Enters A.A by default; however, when an event is declared in A, it should be resolved _relative to A_ not relative to whatever deep state that might be active.

And I disagree with that (in my statechart) that TWO from A.A should end up looing for A.A.B, since the event is declared by the top level A state, not A.A.

**Comment by davidkpiano** [comment]
Edited the above - resolved in the [Gitter](https://gitter.im/statecharts/statecharts) chat. @mogsie's interpretation is correct, and is how `xstate` currently works.

**Comment by MicheleBertoli** [comment]
My two cents: I like the idea of being explicit (e.g. `^foo`) rather than applying a magic resolution algorithm. However, I'm a bit worried about adding too much complexity (e.g. DSL).

I didn't know you were discussing on Gitter, I'll join and read more there :)

Thank you very much, everyone.

**Comment by mogsie** [comment]
We weren't discussing on gitter until we discovered we were on-line at the same time, and it seemed as if we were talking past each other.  github ain't chat! :D

**Comment by katywings** [comment]
I am pretty new to this whole discussion about statemachines but after thinking of ways to solve the transition problem i asked myself if this wouldnt be solveable if the different states would have unique ids (smth. Seperate from the keys)

After experimenting i came to this idea:

js```
// State Constructors which generate a (hidden) unique id and take a string as state key
var yellow = state ("yellow");
var orange = state ("orange");
var red = state ("red");

Machine({ 
  key: 'light', 
  initial: green, 
  states: [
    // created states are setter functions
    green({ 
      on: {
        TIMER: yellow
      }
    }), 
    yellow({
      on: { 
        TIMER: red
      } 
    }), 
    red({ 
      on: { 
        TIMER: green
      } 
    })
  ]
});
```

This would have the following advantages:

- no transition syntax needed
- explicit transitions
- transitions to any state possible
- functional composition of states

Of course this would be a major change, but maybe it would be worth it, long term :).

**Comment by davidkpiano** [comment]
@katywings That's actually a pretty cool idea. Internally, it made me think of two things:

- State nodes already have a (read-only) `id` property, so it might be useful if we could allow the developer to override that.
- We should have some special syntax for targeting an absolute state by its `id`. The obvious one that comes to mind is `#some.state.id`.

By default, the state ID is the full path from its parent; e.g.:

```
{
  key: 'light',
  states: {
    green: {
      // equivalent to TIMER: 'yellow' in this case
      on: { TIMER: '#light.yellow' }
    },
    yellow: { ... }
  }
}
```

But you should be able to do this (in the future, maybe):


```
{
  key: 'light',
  states: {
    green: {
      id: 'green_a1b2c3-fake-uniqueid',
      // equivalent to TIMER: 'yellow' in this case
      on: { TIMER: '#yellow_a4b5c6-fake-uniqueid' }
    },
    yellow: {
      id: 'yellow_a4b5c6-fake-uniqueid',
      // ...
    }
  }
}
```

Which you could sugar with your above proposed functions (passed in as an object instead of an array, for consistency):

```js
Machine({ 
  key: 'light', 
  initial: green, 
  states: {
    // created states are setter functions
    ...green({ 
      on: { TIMER: yellow }
    }), 
    ...yellow({
      on: { TIMER: red } 
    }), 
    ...red({ 
      on: { TIMER: green }
    })
  }
});
```

Where `green({ ... })` would return:

```
{ green: {
  id: 'green_a1b2c3-fake-uniqueid',
  // ... anything else passed in
  }
}
```

I'm wondering if the helper function for this would be best done in userland, though. But overriding `id`s might be a helpful feature.

**Comment by davidkpiano** [comment]
This is now possible using the `id` prop, and `id` notation (e.g., `#foo`) above.
