### ISSUE TITLE
External self transitions are not working for parallel states

### ISSUE THREAD

**Issue by hnordt** [davidkpiano/xstate#531]
## Bug or feature request?

Bug

## Description:

External self transitions are not working for parallel states.

## (Bug) Expected result:

When dispatching an external self transition within a parallel state the machine should make the transition.

## (Bug) Actual result:

When dispatching an external self transition within a parallel state the machine is not making the transition.

## Link to reproduction or proof-of-concept:

https://codesandbox.io/s/trusting-goldberg-i8q9m

**Comment by davidkpiano** [comment]
This looks to be working:

<img width="170" alt="Screen Shot 2019-07-11 at 8 15 05 AM" src="https://user-images.githubusercontent.com/1093738/61050033-05e75c00-a3b4-11e9-8252-9b4820d42451.png">

**Comment by hnordt** [comment]
It’s an external self transition, it should reenter the state.

Click the button multiple times, it won’t work.

**Comment by Andarist** [comment]
The problem lies in the tree combining logic inside `transitionParallelNode` - https://github.com/davidkpiano/xstate/blob/9004cafc6f6ce184595589bdf74d77abd3edba2e/src/StateNode.ts#L742 . It doesn't transfer `reentryNodes` of the computed `transitionMap` to the new combined tree.

If I use the commented out combining logic instead - it works 🎉 However it breaks one other test - https://github.com/davidkpiano/xstate/blob/9004cafc6f6ce184595589bdf74d77abd3edba2e/test/parallel.test.ts#L829
