### ISSUE TITLE
[question] Use promises as guards?

### ISSUE THREAD

**Issue by C5H8NNaO4** [davidkpiano/xstate#533]
Is it possible to use a promise that returns true or false as a guard?

I'm writing a xstate interpreter using the serverless framework. Machines are defined in the serverlesss config and get interpreted by a lambda function triggered by dynamodb stream events. Actions and services are modeled by lambda functions called by the interpreter, which works fine. 

```
StateMachineRedisCache:
  StateMachine:
    id: redis-cache-state-machines
    Source: DynamoDB
    SourceTable: ${self:custom.tableName}
    TableName: ${self:custom.tableName}
    initial: idle
    states:
      idle:
        on:
          MODIFY: cache
          INSERT: cache
      cache:
        invoke:
          src: CacheStateMachines
          onDone:
            target: cached
            actions: ['Log']
          onError:
            target: failed
      cached:
        type: final
      failed:
        type: final
    actions:
      Log: serverless-state-machine-dev-logGlobal
    services:
      CacheStateMachines:
        arn: 
          Fn::GetAtt: [ CacheStateMachineLambdaFunction, Arn ]
```
I would like to implement guard logic using lambda functions but I don't see a way to wait for the asynchronous call to complete before taking the transition.

**Comment by davidkpiano** [comment]
Really cool usage!

> Is it possible to use a promise that returns true or false as a guard?

With state machines and statecharts, all states (including intermediate states) must be explicit. So instead of:

<img width="300" alt="Screen Shot 2019-07-11 at 8 07 16 AM" src="https://user-images.githubusercontent.com/1093738/61049718-2ebb2180-a3b3-11e9-8ca1-1d08dd5de0b3.png">

You would model this with some sort of intermediate "checking" state that invokes the async guard:

<img width="494" alt="Screen Shot 2019-07-11 at 8 08 58 AM" src="https://user-images.githubusercontent.com/1093738/61049734-38448980-a3b3-11e9-8ac6-077a8605cee0.png">

Which might look something like:

```js
CHECKING: {
  invoke: {
    src: 'asyncGuard',
    onDone: 'B',
    onError: 'A'
  }
}
```

**Comment by 3plusalpha** [comment]
@davidkpiano I also stumbled across the guards not being capable of evaluating promises. In my case I have data in a database, which I want to evaluate and I can't load them up-front.

As I use guards quite often creating a CHECKING state would bloat the guards massively (as you need CHECKING state for every single asynchronous piece of code). In this regard allowing promises in guards would make the guard more _useful_.

**Comment by Andarist** [comment]
Every async function has potential of failing and introducing race conditions etc. As @davidkpiano - everything should be modeled **explicitly** and you can't just "skip" some intermediate states. You could try writing some helpers which would automate creating those intermediate states for you, but that could obscure the code - so it's up to you to decide if it's worth it or not.

**Comment by 3plusalpha** [comment]
@Andarist I don't understand exactly how a case that creates a race condition could look like :) 
I assume a failing promise could interpreted as a `falsy` value. But I get your point.
Still, in some other libs (unmaintained though) and also in an old implementation of a state machine at my company (written in Java), asynchronous functions within transitions are not a big deal.

I am also not sure if it is possible to use states within guards - like you proposed. Hmm

**Comment by Andarist** [comment]
Well, mentioning race conditions here might have been an exaggeration on my side. When transitioning to a different state while guard is being evaluated it would just go to the other state and drop the async result of the guard. 

Still I believe that the failing guard should be handled explicitly - it being interpreted as falsy value is IMHO not enough. The decision about what to do in such case should be made by a developer, providing a default (ignoring) would lead to bad practices being incorporated by developers into their machines because using defaults is easy, so many people wouldn't care about handling this scenario.

> I am also not sure if it is possible to use states within guards - like you proposed. Hmm

It is not. I was mentioning that you can hide the proposed pattern:
```js
CHECKING: {
  invoke: {
    src: 'asyncGuard',
    onDone: 'B',
    onError: 'A'
  }
}
```
in a helper. Like - create a `withAsyncGuards` that would take a states definition, parse it a little bit and output a structure which hides this "complexity" in it, so it can be interpreted by XState properly and so you don't have to spread inconvenient pattern across your definition manually if you plan to use this pattern extensively.

**Comment by 3plusalpha** [comment]
Isn't `invoke` exactly the same way like  async guards: you are resolving a promise before you enter a state? Once it's resolved the state machine "fires" the transition event.  `onDone` and `onError` do not require a transition to a new state but instead you can just stay at `CHECKING` state.
( I am already using the invoke pattern in a different context and don't transition to another state)

So in my view xstate already supports this type of `in limbo` state 😉

**Comment by Andarist** [comment]
`invoke` creates a service instance (machine, promise, observable, callback) - but you are free to transition to any state while being in a state which has invoked something. If you stay within that state boundary that invoked service will stay alive, but if you exit it then that service will get automatically canceled. Additionally, there are onDone/onError "shortcuts" - but this just sugar over `.on` (they are just transitions listening for particular done/error events).

**Comment by 3plusalpha** [comment]
I just had a look into the code if it was easily possible to introduce promises, but it actually requires a lot of changes. Pretty sad it's not working

**Comment by Andarist** [comment]
The issue here at hand it's not even about how hard it would be to introduce it - the changes that it would require don't matter much, it's doable. I just believe that we explicitly don't want to introduce it, because we think that it's unnecessary and that it might encourage people to skip error handling etc.

**Comment by davidkpiano** [comment]
> I just had a look into the code if it was easily possible to introduce promises, but it actually requires a lot of changes. Pretty sad it's not working

Like mentioned previously, this is an intentional constraint. An "async guard" is _not_ the same as a simple predicate guard with a promise instead, and there's many things that are easily missed with "async guards":

- What if the async guard times out? How do you handle that?
- What if the async guard returns something other than a `true` or `false`, but some other thing that requires additional action?
- What if you need to handle cancellation?
- How do you test this?

An abstraction can be made in user-land, and it should be. SCXML does not have any notion of async guards, but thinking in terms of "async guards" is probably the wrong way of thinking, anyway. You *want* to have those "in limbo" states explicitly modeled.

**Comment by 3plusalpha** [comment]
In my case: I am running a state machine (in Java) for a dialog / conversation application that contains really a lot of dialogs that branch out to different dialogs if certain conditions (like in guards) match. I think it's really useful and even necessary in my case (like lookups in databases for conditions in guards).

xstate should have become the replacement for the dialog engine as the state configuration is really nice, the state configurations are composable, you can inject guards into existing state configurations, and so. There was a plan to even run chained machines on the frontend and parts on the backend.
Especially guards are really important to us as they are the only way to create non-linear flows based on external data outside of `context`.

**Comment by davidkpiano** [comment]
@3plusalpha I'll try to make an example userland implementation soon. Can you give me an explicit example use-case that I can model?

**Comment by 3plusalpha** [comment]
Ok, I have a real world example of the introduction dialog, which I modelled in xstate (see below).
To send back a dialog item to the user I have some more helper methods, which I left out in this case.

The example shows what dialog should be displayed if a user returns to the app.
All guard conditions are async as we have to check the database.

```
{
  id: "main",
  initial: "start",
  states: {
    start: {
      on: {
        continue: [
          { cond: "isFirstTimeUsage", target: "intro" },
          { cond: "isCheckBackCase", target: "lets_talk_about_your_previous_case" },
          { target: "dashboard" }
        ]
      }
    },
  intro: {},
  lets_talk_about_your_previous_case: {},
  dashboard: {}
}
```

I mentioned `inject guards` earlier and what I mean by this is the ability to create an add more conditions to a guard during configuration time like in the following example.

With this pattern we can break dialogs into smaller entities and still have the ability to `redirect` a flow when external guard conditions match.
I can't really imagine how this could be modelled with approach mentioned above

```
function createAConfig({additionalGuards = []}) {
   return {
      id: 'mySubStateMachine',
      initial: 'firstItem',
      states: {
         firstItem: {
            on: {
               continue: [
                  ...additionalGuards,
                  {target: 'secondItem'}
               ]
            }
         },
         secondItem: {}
      }
   }
}

```

**Comment by Andarist** [comment]
I've started to code this to showcase the idea - have to go out now, but once I get back I'm going to finish this and ping you back

**Comment by Andarist** [comment]
A little bit messy right now - but here it is: https://codesandbox.io/s/inspiring-goldwasser-9ubs3

Main complexity comes from the inability to express dynamic transition targets - had to handle this through explicit transitions on the parent state with raised GOTO events on inner transitions 🤷‍♂

This basically can be also solved differently - a combo of final states and onDone being a guarded transition should also do the trick.

**Comment by 3plusalpha** [comment]
@Andarist thanks a lot for the example! I am thinking now to define an optimized data structure that is tailored for our use case and write a converter that creates a xstate compatible configuration. your code example makes that possible :)

**Comment by Andarist** [comment]
A machine's config is just an object, so it's quite easy to just create factories for them, or parse different formats to it. Possibilities are endless here 🚀 Hope this example was helpful 😃

**Comment by brandonread** [comment]
@3plusalpha, been a while since this thread was active (your example was incredibly helpful!)--wanted to check back and see if you had a chance to fully develop the error-handling, edge-cases, etc.

**Comment by brandonread** [comment]
Looks like there's a [fork here](https://github.com/jfun/xstate/blob/async/src/StateNode.ts#L769) that awaits guard resolution.

**Comment by davidkpiano** [comment]
@brandonread That is not recommended. Async guards are an anti-pattern. You should represent waiting for an async result (whether it is a guard or otherwise) as a state.

**Comment by brandonread** [comment]
Got it--thanks! I'm looking to build a more automated way of scaffolding/configuring machines to enable devs to quickly contribute to a non-deterministic flows with reasonable error-handling by default, without having to worry about whether guards are synchronous/asynchronous. Since I'm leveraging this tool as a wizard layer, I intend to have a consistent experience for clicking "Next" or "Back" in which we may render a loading state during evaluation (given a small timeout to avoid flicker if the promise is instant), or propagate an error-message in a shared parent component in the case the async guard evaluation results in an error.

I'm building upon the approach outlined https://github.com/davidkpiano/xstate/issues/533#issuecomment-543189906--is that an acceptable approach?

**Comment by davidkpiano** [comment]
That approach still uses promises, so no, unfortunately.

**Comment by 3plusalpha** [comment]
@brandonread I actually moved away from async guards in transitions. I created instead a dedicated state that handles async conditions.

You can use this type of guard as an own state and transition to it.

<img width="832" alt="Bildschirmfoto 2020-05-19 um 09 03 39" src="https://user-images.githubusercontent.com/1685307/82295225-b8faeb80-99af-11ea-9368-6ae44b79c247.png">

**Comment by yasirhantoush** [comment]
Oh, I am facing the same problem, I would love to have this feature implemented to make life a bit easier.

I was basically having a multi step (7 forms) wizard each containing a form using Vue with VeeValidator for validation.

However to validate a form, the VeeValidate returns a promise with true / false
I wish I could guard the transition with this promise result.

Implementing this feature would increase the practicality of the library.

**Comment by Andarist** [comment]
@yasirhantoush as mentioned - this is a no go from our perspective, we believe that those intermediate state within „async guard” should not be hidden and should be explicit, because you should think about error handling of such async operations. 

There is nothing wrong about writing your own little abstraction over this in a form of state factory or similar to reduce a boilerplate if you want. Seems like @3plusalpha has gone this route and its great

**Comment by 3plusalpha** [comment]
@yasirhantoush I second what @Andarist is saying. You don't need a "switch" in your transition configuration. You can simply create a "switch" state like follows.

Disclaimer: it's not tested - but you might get the idea

```
const myFlow = {
  initial: 'firstStep',
  states: {
    firstStep: {
      on: {
         next: 'switch'
       }
    },
    switch: {
       invoke: {
          src: Promise.resolve(true),/*  your remote call with Promise */
          onDone: [
             {
               cond: (context, event) => event.data === true,
               target: 'truthyTarget' 
              },
              {target: 'falsyTarget'}
             }
          ],
          onError: 'errorTarget'
       }
    },
    truthyTarget: {},
    falsyTarget: {},
    errorTarget: {}
  }
}

```

**Comment by yasirhantoush** [comment]
@Andarist , @3plusalpha Thanks for the detailed explanation, I did exactly as you stated, I went the path of adding a `checking` state for each form and things went smoothly.

The idea of having multiple targets onDone:[] is fascinating  

Best Regards

**Comment by pranav-planetwalks** [comment]
@davidkpiano I am using workflow and action guards to for-see, next available actions for the users in a given state.

Say, i am in a workflow to publish a response to a question, and before showcasing the publish action to the end user, i need to apply a rule to check if response to question already being made or not, if response already exist, do not allow action on that state.

For this rule check, i have to make persistence queries, but my guard is coming out of async mode. I am not able to use invoke functionality here to for-see actions.

```
{"new": {
                "id": "new",
                "on": {
                    "DRAFT": {
                        "target": "draft",
                        "cond": {
                            "type": "accessGrant",
                            "accessGroup": [
                                "contributorRole",
                                "notanonymous"
                            ],
                            "rules":  {
                                "all": [
                                    {
                                        "fact": "assignmentAlreadySubmitted",
                                        "value": false,
                                        "operator": "equal"
                                    }
                                ]
                            }
                        }
                    },
                    "SUBMIT": {
                        "target": "submitted",
                        "cond": {
                            "type": "accessGrant",
                            "accessGroup": [
                                "contributorRole",
                                "notreviewerRole"
                            ],
                            "rules":  {
                                "all": [
                                    {
                                        "fact": "assignmentAlreadySubmitted",
                                        "value": false,
                                        "operator": "equal"
                                    }
                                ]
                            }
                        }
                    }
                },
                "meta": {
                    "actions": [
                        {
                            "name": "DRAFT",
                            "title": "Save As Draft",
                            "order": 0,
                            "editable": true,
                            "primary": false,
                            "changeViewOnSuccess": false,
                            "successMessage": "Draft saved.",
                            "failureMessage": "Unable to save draft."
                        },
                        {
                            "name": "SUBMIT",
                            "title": "Submit",
                            "order": 0,
                            "primary": true,
                            "editable": false,
                            "changeViewOnSuccess": true,
                            "successMessage": "Request submitted, a moderator will look into it.",
                            "failureMessage": "Unable to submit."
                        }
                    ]
                }
            }}
```

**Comment by davidkpiano** [comment]
@pranav-planetwalks Can you please post this in [discussions](https://github.com/davidkpiano/xstate/discussions)?
