### ISSUE TITLE
[Feedback] Docs Wish List

### ISSUE THREAD

**Issue by davidkpiano** [davidkpiano/xstate#552]
Inspired by https://github.com/davidkpiano/xstate/issues/255#issuecomment-512085968 and other conversations, both online and in person:

**What would you like to see in the documentation?** Let's keep a running list of things that would be beneficial to:

- developers brand new to statecharts
- developers wanting to create new apps/programs with statecharts
- developers wanting to refactor existing apps with statecharts
- experienced developers who want to do more with statecharts (e.g., more powerful type assertions, analysis, testing, etc.)

Some suggestions for things that can be included:

- philosophy/guides on how to "think" in statecharts and the actor model
- example applications
- when to use certain features, like guards or services or actors or transient transitions etc.

**Current suggestions:**

- [ ] TypeScript section for each guide
- [ ] Convert examples to TypeScript
- [ ] Best practices page/section
- [ ] Glossary
- [ ] Patterns and architecture
- [ ] "Build your own" XState (machines, Actor model)

Please post your suggestions 👇 Thank you!

**Comment by nick-walt** [comment]
I've become familiar with the Xstate Docs and really like their style and format. However...

While the sections focus beautifully on implementation details there is virtually no mention of patterns and architecture (other than indicating a relationship with the Actor model).

If there is one thing that helps new learners (especially beginners) it is being able to understand implementation details clearly within the context of patterns and architecture, and in relation to other patterns and architecture.

The Redux Docs are an excellent example of this presentation of detail in context. These two articles, by the same author of the Docs, provide even more context and opportunity for understanding:
 https://blog.isquaredsoftware.com/2017/05/idiomatic-redux-tao-of-redux-part-1/

https://blog.isquaredsoftware.com/2017/05/idiomatic-redux-tao-of-redux-part-2/

I know how hard it is to write good documentation but I think this kind of addition would be of significant benefit. I believe that it would dramatically improve comprehension.

I would like to help if there were an opportunity. Even if it was to give feedback from a beginner's level.

**Comment by nick-walt** [comment]
In my current thinking I see functional programming as a natural fit with both unidirectional data flow and reactivity to observed state changes.

But because of my lack of experience I attempted to find documentation that could help me understand how Xstate's Actor + FSM architecture might be understood in contrast with this view.

I could not. I couldn't see if we were being asked to abandon a unidirectional data design or why.

What also added to this question is that Xstate seems somewhat unique in its own implementation of the Actor model due to being also reactive and functional.

These two aspects did not seem to be native to the various Actor models I was reading about. Those Actor variants appear to promote messaging rather than reactive streams, and an object model over functional model.

While looking for insight into these questions (and more) I have also attempted to understand how Xstate messaging might be wired up to Svelte's native reactivity.

I had no ground on which to stand and orient myself amongst all of this.

**Comment by nick-walt** [comment]
What I see as another natural fit for functional, reactive programming (and the basis of a unidirectional architecture) learning about the CQRS/event sourcing model influenced me significantly.

In the absence of being able to read more in depth about Xstate's own patterns and architecture, I could not come to any understanding or relate it to what else I was learning about.

Although, this document seemed to indicate a natural fit between the Actor model and the CQRS/event sourcing model:
https://doc.akka.io/docs/akka/current/persistence.html

**Comment by avaragado** [comment]
A few thoughts on tech writing in general that might be useful. Apologies if this is all blindingly obvious to you.

- Know who you’re writing for. It’s fine to have some parts written for audience A and some for audience B, but don’t mix them. If you (as the writer) don’t know who you’re writing for, readers will struggle. Be ruthless: in a piece intended for users new to the topic, a deep dive, even as an aside,  will alienate.
- A high-level “10,000 foot” view helps to orient readers: main concepts, important terminology, problems solved. It’s also great as a refresher for returning users.
- Every extra piece of terminology is an additional cognitive load on a reader, and might conflict with the same term used elsewhere. If it quacks, it’s a duck: inventing a new name confuses more than helps. Where overloading is necessary (here, perhaps because SCXML defines a term) highlight the differences from typical usage somewhere handy like a glossary. For example, action and event overlap somewhat confusingly with Redux.
- Examples are incredibly helpful and, because users typically avoid reading, often the only “documentation” they’ll actually look at. Good examples are hard to write. Adding to an earlier example - annotating the code with the changes - reinforces the earlier example and doesn’t force the reader to get their head around entirely new code before they can grasp the point you’re making with that example.
- If you write a sequence of steps, work through them yourself manually, from the same starting point as your readers. Follow your own steps literally and exhaustively, adding and subtracting nothing. Copy and paste code samples, don’t retype. It’s amazing how often you find mistakes and hidden assumptions that you need to mention. 
- For anything intended to be read in sequence - such as a multi-page tutorial - the cardinal sin is to casually use terms you haven’t introduced. These are tricky to spot as you’re familiar with everything already.
- Worry about the learning curve. Too much documentation jumps from simple to complex - from the perspective of your audience - without anything in between. (“Turn on your computer by pressing the power button. Then spawn a shell and vi your hosts file.” If I know what sentence 2 means, sentence 1 is redundant. If sentence 1 is necessary, sentence 2 might as well be Martian.)
- Use simple English. Avoid Latin (eg, ie, etc). Avoid humour. Shorter is generally better.
- Never say “of course”. What’s obvious to you isn’t necessarily obvious to your readers, and can appear smug or patronising. Similar: “it’s really easy,” “don’t worry,” “simply/just do XYZ.”
- Prefer active not passive sentences: “the machine enters state Y” is easier to read than “state Y will be entered [by the machine]” especially for those whose first language isn’t English.
- What, why, who, how, when, where. Keep these in mind at all times. The most common omission is “why”. Why is this important? Why should the reader care? Why does the code do that? Why won’t ABC work?

**Comment by ReasonableDeveloper** [comment]
I want to start by saying that I really love the documentation already.

I would love to have more documentation or examples on TypeScript. Which types to use when passing an `actor`, `service`, just a `send` function, etc. as argument. 

Another thing that could be useful is a `best practices` page where tips are shared on how to write optimal machines. XState is very flexible when it comes to which types it allows for any given key. It would be great to have a dedicated page that shows which ones should best be used for optimal visualization, readability and refactoring.

In the docs, an example of this can be found for [actions](https://xstate.js.org/docs/guides/actions.html#actions)
> Always prefer refactoring inline action implementations in the actions property of the machine options, like the previous example.

A page with reserved xstate keywords like `actions, states` could also be useful.

**Comment by davidkpiano** [comment]
> I would love to have more documentation or examples on TypeScript

Each section in "guides" (when applicable) will have a TypeScript section. I'm also working on simplifying TypeScript types.

> Converting the examples to TypeScript could also help and on top of that would encourage people to use it with XState.

Great idea. I should make some sort of toggle between TS and JS for the code examples.

> a best practices page

I'm making "Tutorials" that shows the best practices in practice, but afterwards I can compile a summary of the best practices. It's just weird (for the reader) to see best practices out of context (e.g., "always avoid this" without a reason why, or an exception).

> A page with reserved xstate keywords like actions, states could also be useful.

Like a glossary? Good idea.

**Comment by ReasonableDeveloper** [comment]
Yes, a glossary of xstate reserved keywords in machines sounds good.
Such list could then also be used to create a vs code extension which syntax highlights the xstate keywords.

**Comment by nick-walt** [comment]
It would be good to have clear guidance on initially implementing pure state machines and charts, with a progression towards adopting the Actor model and Xstate's own state management paradigm.

**Comment by davidkpiano** [comment]
Pure state machines and actor model, sure. Statecharts are a complex algorithm. See for yourself: https://www.w3.org/TR/scxml/#AlgorithmforSCXMLInterpretation

**Comment by nick-walt** [comment]
I've updated my above post to clearly mean Xstate's machines and charts.

**Comment by abierbaum** [comment]
I just found this library today and have gone read all the documentation.  First thing I want to say is thank you so much for the quality of the documentation already.  It is excellent.  Some of the best I have seen.  A couple things I would like to have seen:

   * A high-level summary of all the concepts in a single page or two to help orient to the terminology and what is possible.  (something like: https://angular.io/guide/architecture).  I think this would help orient new users and also help experienced users to see a big picture view and then zoom into what they need.

   * A single place that shows *all* configuration options for a machine on down through each piece.  So for example I can't seem to find a place that shows me every option I could use inside of a state node in a machine definition.  Another way this could be done is maybe a cheat sheet that shows the various options for all the pieces in the machine configuration and references the other items on the page.

   * A recipe for how to use a interpret'ed machine inside an object.  I am coming from a typescript and angular background.  I am looking for a way to add a state machine inside some of my more complex services.  The machine isn't the entire service, it is simply helping to keep track of some core state in the service.  How would I make use of the state machine inside of an object and allow the transitions and actions to make calls on the object?  How should context be setup, should it provide a reference to the object for making side-effects?   

   * Use typescript in some of the examples.  Typescript is awesome, the more of it the better.

**Comment by jjenzz** [comment]
I feel a bit silly posting this but one thing I struggled with was deciding whether something should be a state or a guard. 

My initial understanding was that you declare events in a specific state to "guard" them and transition to those states under correct conditions. However, we can also declare events inside a state that it shouldn't always be able to fire in and use an XState guard to validate the condition before firing. For example:

```jsx
const machine = Machine({
	id: 'myMachine',
	initial: 'form',
	states: {
		form: {
			on: {
				INPUT_THING: {
					actions: ['setThing'],
					target: 'valid'
				},
			}
		},
		valid: {
			on: {
				SUBMIT: ['handleSubmit'],
			}
		}
	}
});
```

versus:

```jsx
const machine = Machine({
	id: 'myMachine',
	initial: 'input',
	states: {
		form: {
			on: {
				INPUT_THING: {
					actions: ['setThing'],
				},
				SUBMIT: { 
					cond: 'isValid',
					actions: ['handleSubmit'],
				}
			}
		},
	}
});
```

I ended up going with the latter for my particular implementation because the `valid` state almost became a replica of the `form` state but I wasn't entirely sure if I had made the right decision there or not.

**Comment by jjenzz** [comment]
> Never say “of course”. What’s obvious to you isn’t necessarily obvious to your readers, and can appear smug or patronising. Similar: “it’s really easy,” “don’t worry,” “simply/just do XYZ.”

Aw man, this made me re-read some of my blog posts and I have a `simply`/`simple` addiction it seems. Need to go away and reword some things 🙈

Thanks @abierbaum. Great write up and suggestions. I'd like to highlight your last point: 

> What, why, who, how, when, where. Keep these in mind at all times. The most common omission is “why”. Why is this important? Why should the reader care? Why does the code do that? Why won’t ABC work?

I've struggled with the "why" in particular from the XState docs. I'm a fully self taught dev so don't have a CS background or any previous experience with State Machines. Some of the concepts/terminologies are a bit hard to grasp and understand the "why" for me at the moment. 

Actors, for example, seem to provide pub/sub communication between machines but this appears to introduce a bidirectional data flow. With React, I'm used to data down, actions up so why would I choose Actors over what I'm used to? Also, is there any harm in just mapping machine actions to React component handlers for that communication if you prefer unidirectional? 

```jsx
const Component = ({ onClick }) = {
	const machine = useMachine(myMachine, {
		actions: {
			handleClick: onClick
		}
	});
	// etc...
};
```

It feels this would keep component concerns separate but it's not clear if that would make my machines brittle in some way or if it's just wrong/frowned upon.

**Comment by stutrek** [comment]
Thanks for this library, I'm having fun learning it and I plan on switching to it for my side projects.

I would like to see documentation of all the options that can be passed to each state, service, etc. Right now I find myself looking through the docs for an example that does what I want, and often finding it as part of an unrelated example.

Add a link to your React Conf 2017 talk, it's the one that sold me and my coworkers on state charts. The price of the book you mention in the talk has fallen to just over $100.

Things I'm struggling with:

- Figuring out parent/child machine relationships and `useService` is hard. I want to put machines with the components that use them, but I am having trouble figuring out how a machine as a service relates to the parent machine's state from `useMachine`. I also find calling a machine a service confusing.
- States have tons of options, but there's no bullet list of them.
- examples. There are only like two and they're quite small. I don't trust that I should be doing things like the todo example.

**Comment by jjenzz** [comment]
https://spectrum.chat/statecharts/general/statecharts-watercooler~4c9e9fb0-74be-4ae0-bf56-e0fcfba903b4?m=MTU2MjkzNDY4MDU5NQ==

> That receiving actor can never update that local state directly 

This was helpful in clearing up my Actors confusion.

**Comment by jeremy-deutsch** [comment]
I'm reading through the docs for the first time and just wanted to make some notes here before I forget:

- The [Getting Started](https://xstate.js.org/docs/guides/start.html) page is a good idea, but it assumes lots of familiarity with both the concepts and the library. It links to other pages when mentioning concepts like machine configuration, transitions, and interpreters, but those other pages are even more dense in library terminology, so condensed inline explanations would be a good idea. For starters, I would remove the reference to hierarchical machines, add a 1-sentence explanation of the transitions, and add a few sentences explaining what an interpreter and service are. I might send a PR for this one after I actually get what these things mean.

- I first tried to approach the docs with a "let's learn by just reading a lot" attitude. But I don't feel a clear progression of what I should be learning first. I started with [Machines](https://xstate.js.org/docs/guides/machines.html), but the Options section confused me, so I followed the links to [Actions](https://xstate.js.org/docs/guides/actions.html) and [Activities](https://xstate.js.org/docs/guides/activities.html), which just confused me more.

- After reading a number of pages, I still have basic questions about the nature of the library. Do state machines have a reference to their current state? If so, what does an interpreter do? The Getting Started page says I need an interpreter in order to "run" a machine, but other pages just call `Machine.transition()` and it looks fine?

- The code examples are very useful now that I've read them, but I tended to glaze over them on my first pass on pages. I hope this doesn't come off too nitpicky, but I think part of it is that the code examples just _look_ very long, even though it's mostly just a lot of:
```
{
  foo: {
    bar: "baz"
  }
}
```
The code examples should maybe be formatted a little differently to give them less of an _appearance_ of being very long. For example, in Machine,
```
states: {
  green: {
    /* ... */
  },
  yellow: {
    /* ... */
  },
  red: {
    /* ... */
  }
}
```
could be
```
states: {
  green: { /* ... */ },
  yellow: { /* ... */ },
  red: { /* ... */ }
}
```
without much trouble.

If I have any more notes as I go, I'll add them to this comment. Really cool library!

**Comment by haywirez** [comment]
I think it'd be useful to add some clarification on how to deal with Typescript in `@xstate.react`.

e.g.:

```TSX
const ComponentWithUseService: React.FC<{
  serviceRef: Interpreter<TContext, TStateSchema, TEvent | AnyEventObject>;
}> = ({serviceRef}) => {
  // ...
  const [current, send] = useService(serviceRef);
  // ...
}
```

or less semantic but also working

```TSX
let [current, send] = useService<TContext, TEvent | AnyEventObject>(serviceRef);
```

**Comment by FredyC** [comment]
I think it would be much nicer to be able to extract those types from the machine itself so we could do `serviceRef: ServiceType<typeof myMachine>`. I don't know exactly how to do that, but something in a similar fashion to ReturnType or Parameters, if it's even possible to tackle generics that way 🤷‍♂

**Comment by Blacktiger** [comment]
I noticed today that the spawn API is never really documented. You can get a lot of information from the "actors" guide, but the options are never described directly. In particular, the autoForward option isn't talked about but it would be nice to have an API doc somewhere that covers name, sync, and autoForward.

**Comment by thomas-m-andrus** [comment]
Could you include a more complex Typescript example? Maybe a todo list that is fully in typescript, where models, actions, guards, and services are separated into their own files and imported into the machine file. I was having particular trouble with creating an adequate model for a service, defined outside of the original file, and invoked in the machine. I eventually dropped the invoke entirely and called the service from one of the transitions. In general, more xstate examples, especially complex ones (in typescript), would give me greater confidence in creating machines and also steering teammates towards xstate. Thank you for your time and consideration!

**Comment by chancestrickland** [comment]
On the topic of TypeScript examples, it could be nice (and possibly automated?) if code snippets could be illustrated in both TS and JS. I see that this gets asked about a lot, so perhaps this could reduce the number of TS-related issues and questions coming in as well. Perhaps doable without cluttering up the screen by using tabs at the top of each code element that toggle between the two?
