### ISSUE TITLE
[Recipe] Service Hooks

### ISSUE THREAD

**Issue by hnordt** [davidkpiano/xstate#572]
A nice little "pattern" I've been following is to use React hooks to further decouple machines from the UI. That way UI doesn't need to know anything about the machine structure.

If you need to change a specific machine structure in a fundamental way, it becomes really easy to update the single UI hook that talks to this machine.

Here's an example:

```js
// (extracted from the TodoMVC example)

function Todos() {
  let [state, send] = useMachine(persistedTodosMachine)

  let { todos, todo } = state.context

  let numActiveTodos = todos.filter(todo => !todo.completed).length
  let allCompleted = todos.length > 0 && numActiveTodos === 0
  let mark = !allCompleted ? "completed" : "active"
  let markEvent = `MARK.${mark}`
  let filteredTodos = filterTodos(state, todos)
}

// becomes...

function usePersistedTodos() {
  let [state, send] = useMachine(persistedTodosMachine)
  let { todos, todo } = state.context

  let activeCount = todos.filter(todo => !todo.completed).length
  let allCompleted = todos.length > 0 && activeCount === 0

  let completeAll = () => send("MARK.completed")
  let uncompleteAll = () =>  send("MARK.active")
  let filterTodos = () => filterTodos(state, todos)

  return {
    activeCount,
    allCompleted,
    completeAll,
    uncompleteAll,
    filterTodos
  }
}

function Todos() {
  // This UI component doesn't know anything about the machine structure.
  // It's just using a hook, it doesn't even know that we are using XState 3, 4 or 5.
  let {
    activeCount,
    allCompleted,
    completeAll,
    uncompleteAll,
    filterTodos
  } = usePersistedTodos()
}
```

There's nothing special about it. For each `useMachine` or `useService` you might create a service hook (service in the sense of an interpreter instance).

These service hooks acts as an additional layer, so it's kind of an additional layer of indirection. But it can improve code reuse, it might make easier to refactor complex machines, and it can help to easily upgrade to XState major versions.

**Comment by davidkpiano** [comment]
This is great for developer experience in many cases; however, with names like `completeAll`, `uncompleteAll`, etc., it doesn't exactly fit in the state machine paradigm of describing events: events should describe what just happened, not what should happen (because the desired result might not happen). It becomes more imperative than the idea of "sending an event" - which is more explicit and clear that the event might not have the intended effect.

A good compromise would be naming these abstractions `sendCompleteAll`, etc. which more fit the "sending an event" idea.

In any case, these abstractions are up to the developers and XState should not try to impose an opinion on this.

**Comment by hnordt** [comment]
I liked the `sendEventName()` idea.

The recipe is not a way to impose opinion, it's just a suggestion on how you could further decouple the UI and machine by using React hooks. The reader is free to use the idea, improve, or just ignore it.
