### ISSUE TITLE
Assign actions being called with stale meta

### ISSUE THREAD

**Issue by Andarist** [davidkpiano/xstate#593]
## Description:

The newly implemented meta argument for assign actions is being called with a stale state. Because assign is just an action (like others), with just a single special rule - that they are executed first, it should be called with the same values (context, event, meta) as other actions

## (Bug) Expected result:

Assign actions being called with updated state.

## (Bug) Actual result:

Assign actions being called with stale state.

## Link to reproduction

https://codesandbox.io/s/goofy-allen-id9ju

**Comment by davidkpiano** [comment]
This is expected because `assign()` actions happen on the microstep and other actions happen on the macrostep (after all microsteps have been taken).

Contrived sequence of events:

```
state 1
 ⬇
(EVENT)
 ⬇
- assign (called with state 1)
- assign (called with state 1)
- raise
- assign (called with state 1)
 ⬇
state 2
- action (called with state 2)
- action (called with state 2)
```

The most updated state (`state 2` in the above example) cannot be determined until all of the "raised events" (in SCXML lingo) are processed. That `state 2` is what is passed on to actions, which occur afterwards.

**Comment by Andarist** [comment]
Let's keep the discussion open for now - seems to me that there still something off regarding action resolving right now, although I believe another issue should be reported (both actual & expected results described here - by me - are probably wrong).

According to the SCXML spec microstep actually should resolve all its executable content - https://www.w3.org/TR/scxml/#microstepProcedure . And thus this behaves incorrectly now - https://codesandbox.io/s/damp-architecture-4m6jc - because actions shouldn't be batched to get executed after machine settles, but rather they should get executed while it's processing.

**Comment by davidkpiano** [comment]
The alternative resolution is this:

```
state 1
 ⬇
(EVENT)
 ↓
state 2 (temp 1)
 ↓
- assign (called with state 2 temp 1)
 ↓
state 2 (temp 2)
 ↓
- assign (called with state 2 temp 2)
 ↓
state 2 (temp 3)
 ↓
- raise (called with state 2 temp 3 - might transition!)
 ↓
state 2 (temp 4)
 ↓
- assign (called with state 2 temp 4)
 ⬇
state 2
- action (called with state 2)
- action (called with state 2)
```

The potentially confusing (but correct) part is that e.g., `state 2 (temp 1)` is _not_ equal to `state 2 (temp 2)`, and can even have a completely different state value than `state 2 (temp 4)` (called after a raised event).

**Comment by Andarist** [comment]
https://github.com/davidkpiano/xstate/issues/603 seems more suitable for this discussion - closing this in favor of the other one.

**Comment by mrjogo** [comment]
Since it is by design that the assign meta argument has the previous state even when part of an `entry` action, what's the right way to do an assignment that needs the new state value?

My specific use case is I am storing an object per state in the context, with the state name as the key, and upon entry of each state, I want to call a method on the corresponding object and store the result in a `currentResult` context key. Here is basically what I am trying to do:
```javascript
const setCurrent = (ctx, evt, meta) => ctx.entities[meta.state.value].someMethod();

{
  initial: "State1",
  context: {
    currentResult: null,
    entities: {
      State1: state1Instance,
      State2: state2Instance,
    },
  },
  states: {
    State1: {
      entry: assign({ currentResult:  setCurrent }),
      on: { DONE: State2 },
    },
    State2: {
      entry: assign({ currentResult:  setCurrent }),
      on: { DONE: State1 },
    },
  }
}
```

I can't store the `entities` in the state metadata because they are assigned in other states (not shown here). Suggestions?

**Comment by davidkpiano** [comment]
@mrjogo Can you give a more general, real-life example of what you're trying to accomplish? There might be a better way.
