### ISSUE TITLE
promise rejection 'error.execution' does not happen

### ISSUE THREAD

**Issue by serge-sedelnikov** [davidkpiano/xstate#618]
## Bug or feature request?

Bug: on promise sevice rejection interpreter does not get the event.type === 'error.execution'

## Description:

in version 4.5.0 it was OK, every time onError call is specified, the interpreter on Transition received the event.type === 'error.execution'. I updated to version 4.6.7 (latest) and it never happens anymore (event.type === 'error.execution'), but the data property of the event still contains error object

## (Bug) Expected result:

on Promise service rejection to have event.type === 'error.execution' as before

## (Bug) Actual result:

event.type === 'current.state.service.invocations[0]'

## (Bug) Potential fix:

**Required!** If you found a bug and can consistently reproduce it, please take a minute to think about what the potential fix might be.
Even if the fix is incorrect, this can help diagnose and find the solution to the issue as quickly as possible.

I also strongly encourage you to [create a pull request](https://github.com/davidkpiano/xstate/pulls) if you are confident in the potential fix.

## (Feature) Potential implementation:

**Required!** If you would like to see a feature or enhancement make its way to xstate, please describe:

- What the API would look like
- If this is a breaking change
- If this is part of the existing [SCXML specification](https://www.w3.org/TR/scxml/)

## Link to reproduction or proof-of-concept:

You can use [CodePen](codepen.io) or [CodeSandbox template](https://codesandbox.io/s/6dsws) to create a reproduction/POC.

**Comment by Andarist** [comment]
Previously errors received wrong type - `error.execution` is supposed to be for synchronous expression evaluation errors. This means it should be raised when Machine is not valid or when you have a runtime error in one of your actions, guards etc.

For a promise we need to use another error type as promise might be validly rejected, not because of a programming error. It allows us to only call appropriate onError handler - instead of calling it on all parallel states.

I've prepared a quick demo - https://codesandbox.io/s/blissful-chaplygin-hlynb and from what I see `onTransition` gets called with proper `error.platform.(machine).bar:invocation[0]` type.

Keep in mind that you shouldn't rely much on internal error types yourself. Could you describe your use case for that? What are you trying to achieve?

**Comment by serge-sedelnikov** [comment]
well that explains the case, I will change the logic of my code. What I used the xstate for is the hardware acceptance tests that tries to run a certain procedure on the hardware and throws Error in case of failure, hence I consider the test is failed.

Your explanation changes the vision but does not limit me to fix my code. And yes I agree that rejecting the Promise is not necessary the error.

I think this can be closed.

**Comment by serge-sedelnikov** [comment]
also thanks for that

> onTransition gets called with proper error.platform.(machine).bar:invocation[0] type.

Did not notice that `error` word before

**Comment by Andarist** [comment]
Glad you can adjust your logic without much trouble 👍
