### ISSUE TITLE
Duplicate actions on batched events in a parallel machine

### ISSUE THREAD

**Issue by xiranou** [davidkpiano/xstate#619]
## Bug or feature request?
Maybe a Bug?

## Description:
Not sure if this is an expected behavior as I don't have a good grasp on batched events yet . 🙏 

When you send batched events to a machine with parallel states, the machine is able to reach the expected states but the actions seems to be remind after transition. This leads to the same action being appended again on the next transition.

Example:
https://codesandbox.io/embed/gracious-sunset-950ut

## (Bug) Expected result:
Actions to be cleared on transition

## (Bug) Actual result:
Actions are not cleared on transition

**Comment by davidkpiano** [comment]
This is expected behavior; it's like telling someone "flip that light switch on then off then on again" - it's going to ultimately be on, but those transitions are still going to occur sequentially, and the "light turning on" action will still be done twice.

You might be looking to use [activities 📖](https://xstate.js.org/docs/guides/activities.html) instead.
