### ISSUE TITLE
xstate/react context initialization

### ISSUE THREAD

**Issue by hnordt** [davidkpiano/xstate#640]
This line:

https://github.com/davidkpiano/xstate/blob/97097799d5b3fb9086104421da1754eedd8f7339/packages/xstate-react/src/index.ts#L64

Shouldn't be `machine.initialState.context`?

I can make a PR.

**Comment by davidkpiano** [comment]
In this case, it's actually not, because the `initialState.context` can differ from the configured `context`.

The `initialState` factors in transient transitions as well, which can change the context from its configured `context`, and we only want to take the configured `context` into account.

Is this resulting in any unexpected behavior? It shouldn't.

**Comment by hnordt** [comment]
Thanks!
