### ISSUE TITLE
Bug: onTransition not firing for 'after' action when execute=false

### ISSUE THREAD

**Issue by aaron-manning** [davidkpiano/xstate#668]
## Bug or feature request?
Bug
## Description:
Interpreted machines with {execute: false} are not triggering 'after' events on 'onTransition'. This makes it impossible to use 'after' (and possible 'delay' too) as no action can be picked up in the event handler.
## (Bug) Expected result:
a transition is fired but the action handling is left to the user's implementation.
## (Bug) Actual result:
no transition is fired

## Link to reproduction or proof-of-concept:
https://codesandbox.io/embed/xstate-typescript-template-tvqns

Loving xState! great work.
If there is a known workaround for this issue?

**Comment by amanning11** [comment]
That's great thanks. Missed that you can manually call the internal execute function in the docs.

**Comment by Andarist** [comment]
> If a transition is set to fire 'after' 5000ms, one would expect to see the transition after said time, not immediately.

Transition after would be observed if you would execute that send action. The immediate transitions is a different transition - and it should be observed too, it's the one which causes a state with `after` to be entered.

**Comment by amanning11** [comment]
I'm new to using state machines and conceptually a 'send action' doesn't sound like a transition, which is why i expected to only see the result of the send action in the onTransition handler.

Now i understand why this is the case.
Thank you all for your help. I have resolved the issue by manually calling 
`service.execute(state);`
