### ISSUE TITLE
nextEvents on state is not filtered based on guards 

### ISSUE THREAD

**Issue by Sunil6591** [davidkpiano/xstate#669]
## Bug?
`nextEvents` on state is not filtered based on guards 
## Description:
E.g. Here is part of my machine
```
...
partial: {
      on: {
        AUTO_PAY: 'checkWalletBalance',
        TOP_UP: {
          target: 'addToWallet', cond: context => context.openBalance > 0,
        },
        BOUNCE: 'bouncePayment',
        GEN_NUMBER: {
          target: 'genInvoiceNumber', cond: context => !context.invoiceNumber,
        },
        REGEN: 'regenInvoice',
        MOVE_TO_WALLET: {
          target: 'moveToWallet', cond: context => context.openBalance !== 0,
        },
        APPROVE: {
          target: 'approveInvoice', cond: context => !context.approved,
        },
        AUTO_APPROVE: {
          target: 'autoApproveInvoice', cond: context => !context.approved,
        },
        REJECT: 'rejectInvoice',
        APPROVE_CHANGES: {
          target: 'approveAmmendments', cond: context => context.ammendment,
        },
      },
    },
    unpaid: {
      on: {
        AUTO_PAY: 'checkWalletBalance',
        TOP_UP: {
          target: 'addToWallet', cond: context => context.openBalance > 0,
        },
        REGEN: 'regenInvoice',
        GEN_NUMBER: {
          target: 'genInvoiceNumber', cond: context => !context.invoiceNumber,
        },
        MOVE_TO_WALLET: {
          target: 'moveToWallet', cond: context => context.openBalance !== 0,
        },
        APPROVE: {
          target: 'approveInvoice', cond: context => !context.approved,
        },
        AUTO_APPROVE: {
          target: 'autoApproveInvoice', cond: context => !context.approved,
        },
        REJECT: 'rejectInvoice',
      },
    },
...
```
Now when machine is transitioned from `unpaid` to `partial`, the `onTransition` event gives the transitioned state. So when `console.log(state.nextEvents)` it prints out all possible events on `partial` state. So e.g. if the context already has `invoiceNumber` in that case the `GEN_NUMBER` shudnt be part of `nextEvents` as after evaluating the guard on `GEN_NUMBER` it shud be filtered out.
## (Bug) Expected result:
In case `context` has `invoiceNumber`
```
nextEvents => [ 'AUTO_PAY',
  'TOP_UP',
  'BOUNCE',
  'REGEN',
  'MOVE_TO_WALLET',
  'APPROVE',
  'AUTO_APPROVE',
  'REJECT',
  'APPROVE_CHANGES' ]
```
## (Bug) Actual result:
In case `context` has `invoiceNumber`
```
nextEvents => [ 'AUTO_PAY',
  'TOP_UP',
  'BOUNCE',
  'REGEN',
  'GEN_NUMBER',
  'MOVE_TO_WALLET',
  'APPROVE',
  'AUTO_APPROVE',
  'REJECT',
  'APPROVE_CHANGES' ]
```
## (Bug) Potential fix:
`nextEvents` shud be filtered based on guard conditions

**Comment by davidkpiano** [comment]
It's impossible to filter `nextEvents` based on guard conditions, because guard conditions rely on both state (`context`) _and_ the event that triggers the transition. And there is no way of knowing what the next event is going to be (we can't predict the future).

But if you want to base it just on context, that can be done in user-land, by trying out each `event` in `nextEvents` (`machine.transition(state, nextEvent)`) and filtering by whether the resulting `nextState.changed === true`.

Related to #663

**Comment by Sunil6591** [comment]
if `nextEvent` is valid event then `machine.transition(state, nextEvent)` will change the machine to next state, which is not expected. All i want is to check the condition on event if it is allowed to execute, accordingly I can hide/show events on UI

**Comment by Andarist** [comment]
Machine is a pure API - it doesnt change anything. For it to work it has to receive current state and stuff and based on that it returns next state which u have to cache to feed into next machine calls if u want to implement executable service. This is exactly what Interpreter does.

You can either access (pure) machine existing on your interpreter’s instance and query it in a way u want or u can ie use this API:
https://github.com/davidkpiano/xstate/blob/071b51636a87dc983c71714ad7dede89081d4f78/src/interpreter.ts#L614

**Comment by WangLarry** [comment]
```

  const [current, send, service] = useMachine(questionsMachine);
  
  const enableBack = React.useMemo(() => {
    const res = (current && service.nextState("BACK").changed);
    return res;
  }, [current, service]);

```

**Comment by Yuyz0112** [comment]
Sorry for appending to a closed issue.

But I've found the `nextState.changed === true` check is always false when I'm doing an external self transition without side effect. And I think it should be considered as a valid next event since the transition actually happened.

Currently, I'm using `nextState.transitions.length > 0` to do the trick since I always create a new state and do a transition for guard checking.

**Comment by davidkpiano** [comment]
> Sorry for appending to a closed issue.
> 
> But I've found the `nextState.changed === true` check is always false when I'm doing an external self transition without side effect. And I think it should be considered as a valid next event since the transition actually happened.
> 
> Currently, I'm using `nextState.transitions.length > 0` to do the trick since I always create a new state and do a transition for guard checking.

What is your use-case here? You can always ignore `nextState.changed` and do whatever you need to do on the next state, but it is true that the state has not changed.

**Comment by Yuyz0112** [comment]
@davidkpiano my use case is to find the next events that can pass the guards.

```
{
  stateA: {
    on: {
      EVENT_1: {
        internal: false,
        guard: 'myCondition';
      }
    }
  }
}
```

In `stateA`, EVENT_1 will be in the nextEvents array. And when I try to figure out whether EVENT_1 can pass the guard(to tell UI EVENT_1 is an valid action), `nextState.changed` does not works as this:

> But if you want to base it just on context, that can be done in user-land, by trying out each event in nextEvents (machine.transition(state, nextEvent)) and filtering by whether the resulting nextState.changed === true.

Because changed stay to false. So I check the transitions array.
