### ISSUE TITLE
Null Event listeners supressing onEntry and onExit actions

### ISSUE THREAD

**Issue by chrisjallen** [davidkpiano/xstate#723]
**Description**
Upon any transition into a new state, the onEntry action for the target state is ignored if the state also implements any transient transitions. Its quite unclear from documentation on expected execution order and behaviours when this is implemented. 

Example: 
I have one state (requesting) that onDone, transitions to next state called 'processing'. This state checks that the data sent via request is valid and then transitions to either states 'withResults' or 'noResults' based on a guard. I expect to store the event data supplied from 'requesting' state in an onEntry. Then I use a transient transition to 'decide' the data's validity using a 'gotResults' guard of some kind, deciding the final 'hasResults' or 'noResults' state.

``` 
   ...
   requesting: {
     invoke: {
         src: 'someReusableRequestMachine',
         onDone: 'processResults',
         onError: 'failedRequest
    } 
  },

  processResults: {
      onEntry: 'storeResults',
      on: {
         '':  [
             { target: "hasResults", guard: "checkResultsValid" },
            { target: "noResults" }
        ]
     }
 },

 hasResults: {},
 
 noResults: {},

 failedRequest: {}

}

```
 
**Expected Result**
Expect the state + method execution order to be:
```
  state -> Requesting => 
  state -> processResults => 
      onEntry -> 'storeResults' : stores request data to context  => 
      transition guard -> 'checkResultsValid' : checks request data from context => 
   state -> hasResults|noResults
 ```

**Actual Result**
The onEntry (or any onExit for that matter) is ignored.
``` 
  state -> Requesting => 
  state -> processResults => 
      transition guard -> 'checkResultsValid' : no request data in context => 
   state -> noResults 
 ```
checkResultsValid is called without the 'storeResults' storing the data, so it returns false as it cant get the data from its own context. 

**Reproduction**
 n/a can supply if needed, should be quite readable.

**Additional context**
The difficult part is understanding if this is expected behavior, I would assume that it would be logical for the onEntry and onExits to be fired before any other action can be called. I basically need a means of storing something before using a guard to check, even if I create another inbetween state to store the data, this wont work as the same problem appears where by in order to transition to next state, I need a transient transition, and this would suppress the onentry. I could implement an action in the transition transition target object, but this always gets called after the next transition is made, making the call too late to store any data deemed useful.

If it is a bug, if there is any way of me helping with correcting this bug, any details on likely place in codebase would be most welcome.

**Comment by Andarist** [comment]
Could you prepare a repro case? Please don't assume that the ticket is readable and actionable without it - it might be, but diving into it without repro might often take more time for a maintainer of a particular library and unfortunately, we have more too handle than a single ticket - so every help (in this case - some work made by reporter up front) is really valuable for us. 

**If** I understand the reported issue correctly - then yes, entry actions should be executed, eventless transitions shouldn't affect it anyhow (if my understanding of SCXML spec is correct, but I think it is). I can't be sure though if you suffer from a bug here though, because I can't check actual behavior quickly.

**Comment by chrisjallen** [comment]
thanks Ill post up demo

**Comment by chrisjallen** [comment]
Ok created two examples, one on code sandbox and the other through xstate visualiser. 
Very interesting, the code sandbox is showing the bug, but visualiser is firing many 'checkResults' before and after the onEntry action. Codesandbox... showing bug, visualiser... working as expected.


https://codesandbox.io/s/xstate-example-template-lo8y5?expanddevtools=1&fontsize=14
https://xstate.js.org/viz/?gist=44dafd4d5b4b8ca00138d3f919694903

Ive attached both console outputs to show discrepancy, could this be different xstate versions and the latest not working (Im currently see this bug in 4.6.7, not sure what the visualiser tool is running).

codesandbox console: showing bug 
<img width="783" alt="Screenshot 2019-10-11 at 19 49 59" src="https://user-images.githubusercontent.com/517927/66676743-18498e00-ec60-11e9-9b70-0c4228b694ad.png">

visualizer tool console: not showing bug (working as expected)
<img width="951" alt="Screenshot 2019-10-11 at 19 50 48" src="https://user-images.githubusercontent.com/517927/66676745-18e22480-ec60-11e9-8e68-dbf9abd8d9d6.png">

**Comment by Andarist** [comment]
To modify your context data you should use `assign` action. We prefer not to mutate data. Fixed sandbox here:
https://codesandbox.io/s/xstate-example-template-ggs53

**Comment by chrisjallen** [comment]
Thanks so much for looking into this @Andarist. This definitely fixes up my context assignment and the original problem, however it still doesn't feel right, essentially an assign would get called with a different execution order to an onEntry action/inline function.

It feels I came to this problem due to the assumption that onEntry would always be the first function called. If I wasn't assigning context, I would still want this onEntry action to be fired first. There seems to be a lack of documenting these execution orders/lifecycles, happy to help contribute with documentation but still unclear on execution differentials. 

The difference between my example and your fork demonstrates the following execution difference:

onEntry with simple arrow function (action type)
--
1) checkResultsValid guard
2) onEntry
3) state to noResults due to onEntry fired AFTER 

onEntry with assign creator (@Andarist your fix)
--
1) onEntry
2) checkResultsValid guard
3) state to hasResults 

I would still place this as a bug as I would expect these action executions to be deterministic, or at least in the same order.

**Comment by Andarist** [comment]
Well, you have encountered here a little bit problematic case. Currently `assign` action is treated specially - it's always evaluated first and within Machine internals when `.transition` gets called. Other actions are gathered together and given to the Interpreter (so after it receives `.transition` result from the Machine) so it can execute them.

At the same time, transient transitions (and raised events) are also handled within that `.transition` call internally so you might notice some execution order quirks - this particular example doesn't suffer from this much.

The current logic is a little bit flawed and prevents us from being 100% compatible with SCXML (which is the goal) and we'll be dropping it in the next major version - all actions should be called in an order they appear in the machine definition, adhering to exit/transition/enter order etc - but no action should be special-cased to be handled differently.

While the plans are to change the behavior it shouldn't hopefully matter for you that much - or I haven't yet encountered a much realistic scenario when this really makes a difference. The main problem right now is that exit actions are executed with updated context (when it gets updated by e.g. entry actions - which technically is not correct because entry actions happen after exit actions)

**Comment by chrisjallen** [comment]
Ok thanks @Andarist, that makes sense, I agree I would expect the onEntry/Exit calls to fire first ahead of transition actions. Not sure on where to lead this defect but leave to you and @davidkpiano to decide if needing opening into separate bug. Thanks again

**Comment by Andarist** [comment]
There is already open ticked for this - https://github.com/davidkpiano/xstate/issues/603

Keep in mind also that the correct order of actions is: exit -> transition -> enter, as per: https://www.w3.org/TR/scxml/#microstepProcedure
