### ISSUE TITLE
Spawning machines on entry action doesn't work (4.7.0-rc5)

### ISSUE THREAD

**Issue by allforabit** [davidkpiano/xstate#757]
**Description**
I've been playing around with the next release of xstate and the new features are looking great. One issue I've noticed is spawning machines on an entry action doesn't seem to be working.

**Expected Result**
Spawning a machine in an assign action should create a machine and save it as a ref in context.

**Actual Result**
Xstate gives a warning about spawning new machines outside of an assign and doesn't spawn the machine.

**Reproduction**
https://codesandbox.io/s/hopeful-franklin-8z0t6

**Additional context**
Create with 4.7.0-rc5

**Comment by jeffsee55** [comment]
@allforabit I've noticed this issue but I think it's slightly different from what you've described. 

Spawning a machine does seem to work properly, I think what you're seeing is some react-specific issues relating to the `ref` prop on a function component. If you change the prop name to anything else (ex. `machineRef`) things work properly - however the warning remains.

Here's your codesandbox updated to use `machineRef` instead of `ref` as a prop - https://codesandbox.io/s/wandering-dust-7i6tx

So from what I'm seeing it seems like the warning shouldn't be there at all - the Todo works properly and can send messages to the parent.

**Comment by Andarist** [comment]
@allforabit thanks for the repro case for the unnecessary warning being logged to the console. I've prepared a fix for this https://github.com/davidkpiano/xstate/pull/758
