### ISSUE TITLE
Send to child invoked machine with id not working

### ISSUE THREAD

**Issue by MrColdfinger** [davidkpiano/xstate#805]
**Description**
First of all thank you for this incredible library!

According to the [documentation](https://xstate.js.org/docs/guides/actions.html#send-targets), it should be possible to send to a specific target with the `id`? When setting up a machine with a state that invokes another machine, using the parent `send(..., { to: ... })` doesn't seem to trigger the child event. I'm not sure if this is a bug or if I'm doing something wrong...

**Expected Result**
Expect the child event to fire.

**Actual Result**
Nothing happens.

**Reproduction**
Here's a simple [reproduction of the issue](https://codesandbox.io/s/xstate-example-template-9zrvz?fontsize=14&hidenavigation=1&theme=dark).

**Additional context**
xstate version 4.6.7

**Comment by Andarist** [comment]
The problem here is that you are not using `send` action, but rather an interpreter's send method and those are different things.

I think often explicit message passing should be preferred - you could send an event to your "root" service which in turn could forward it to its child (with targeted send action). But if you want to bypass the "root" service and want to send an event to its child directly then you can do this:
```js
service.children.get('child').send("FINISH");
```
