### ISSUE TITLE
Working with action parameters in Vizualizer

### ISSUE THREAD

**Issue by PetrSnobelt** [davidkpiano/xstate#818]
👋 Hi, I'm new to xstate, so maybe what I'd like trying to do is not the best approach...

## Bug or feature request?
 probably feature request

## Description:
 It would be great if you can try actions with parameter in the visualizer

## Sample
I have such a simple state machine, which should let you add numbers until context count is 10:
```
const sumToTenMachine = Machine({
  id: "summer",
  initial: "counting",
  context: {
    count: 0
  },
  states: {
    counting: {
      on: {
        ADD: [
          {
            cond: (context, { no }) =>
              no > 0 && context.count + no <= 11,
            actions: assign({
              count: ({ prevCount }, { no }) => prevCount + no
            })
          },
          {
            target: "success",
            cond: (context, { no }) => context.count + no === 10,
            actions: [
              assign({
                count: ({ prevCount }, { no }) => prevCount + no
              })
            ]
          }
        ]
      }
    },
    success: {
      type: "final"
    }
  }
})
```

But if I'd like to try it in the visualizer, it is not possible (or I don't know how to do it) because I cannot specify "count" param in the visualizer

**Comment by Andarist** [comment]
This is indeed somewhat a problem with how visualizer works now. This particular case is broken because visualizer classifies both as invalid transitions - in a sense that their guard cannot be satisfied at the moment.
https://github.com/statecharts/xstate-viz/blob/9c50ad32497e36b46b34031962372a5427af2b2f/src/StateChartNode.tsx#L641-L648

One of the problems I see there is that guards are being eagerly evaluated with `current.event` - but this is not the event they should be tested with, in a real app. Those guards should be evaluated with "future" events - which is of course impossible. Seems like we should rethink how we handle guards in the viz in general.

**Comment by davidkpiano** [comment]
This is possible in the visualizer already:

<img width="384" alt="Screen Shot 2019-11-24 at 8 12 56 AM" src="https://user-images.githubusercontent.com/1093738/69495198-42fb4900-0e92-11ea-9b33-6ccc5600eb8b.png">

Also, your logic will always take the first condition, because even when `event.no === 10`, the first condition will pass, and it will never transition.

**Comment by PetrSnobelt** [comment]
Thanks for quick response

**Comment by Andarist** [comment]
@davidkpiano there is still an issue of guards being evaluated against wrong events

**Comment by davidkpiano** [comment]
@Andarist That's probably a separate issue

**Comment by PetrSnobelt** [comment]
@Andarist I try to address it in https://github.com/statecharts/xstate-viz/pull/47
