### ISSUE TITLE
@xstate/test feature request: withTestMeta helper method

### ISSUE THREAD

**Issue by axelnormand** [davidkpiano/xstate#979]
Firstly thanks for such a great library. Was inspired by your write fewer tests talk to try and use xstate in our production code.
Just trying it our for now in a small react native project to drive react navigation for some user journeys

I wanted to use the same machine for the implementation, detox e2e tests and jest tests as inspired by your excellent talk.

I was wondering the best way to do this? ie in detox and jest i need to specify different `meta.test` implementations for each state to grab appropriate elements and verify they're there for the test to pass. 

At the moment i have a factory method to create the same machine but apply different `meta.test` keys.

I thought it'd be useful for `@xstate/test` to have some helper method like `withEvents` maybe called `withTestMeta(stateMap)` or something?

`stateMap` being a mapping of every state to a function as you would implement in `meta.test`.  Get's more complex for nested machines mind.
 It would be great for such a method to be typed to so you don't miss a state too.

From a brief scan of the source i don't think you can specify different meta `test` keys? That could be another approach. ie `meta.testJest` and `meta.testE2e` perhaps, then instantiate the test model and pass in the test meta key to use?

I'm happy to attempt a PR but wanted anyones thoughts on this approach or how they tackled the same thing. 
Thanks.

**Comment by davidkpiano** [comment]
Hey, thanks!

In general, you should create _separate machines_ for implementation and testing. Your testing machine should be as a user would perceive your app to work (thus removing all the implementation details) - so if your implementation machine changes, the testing machine should definitely break (as expected). And then you would change your testing machine to match the new expected behavior.

However, I can see there being some sort of `extendMachine()` helper function. For now, this is best done in user-land.

If you can share how you're doing it, I'd be more than happy to put it in the docs!

**Comment by axelnormand** [comment]
Many thanks for the reply!
Will share my little test repo shortly.

Sorry all a bit new to state machines. Why is it better to create a separate test machine?
In this case anyway it's pretty cool to change the user flow, not have to do anything to the tests, and they still test all paths? (assuming no new states i need to add `meta.test` keys for anyway)

**Comment by axelnormand** [comment]
`extendMachine` would deffo still be useful i this case if i create a test machine, can be consumed by both e2e and unit tests then

**Comment by expelledboy** [comment]
> In general, you should create _separate machines_ for implementation and testing. Your testing machine should be as a user would perceive your app to work (thus removing all the implementation details) - so if your implementation machine changes, the testing machine should definitely break (as expected). And then you would change your testing machine to match the new expected behavior.

Hi new to xstate, and I am struggling to understand this statement. Why would you _want_ to duplicate the entire state engine config?

**Comment by davidkpiano** [comment]
> > In general, you should create _separate machines_ for implementation and testing. Your testing machine should be as a user would perceive your app to work (thus removing all the implementation details) - so if your implementation machine changes, the testing machine should definitely break (as expected). And then you would change your testing machine to match the new expected behavior.
> 
> Hi new to xstate, and I am struggling to understand this statement. Why would you _want_ to duplicate the entire state engine config?

See here for more info: https://github.com/davidkpiano/xstate/discussions/1311

**Comment by expelledboy** [comment]
@davidkpiano Okay still trying to determine how best to use `@xstate/testing`. If I understand correctly it is pointless directly testing a state machine with `xstate/testing`?

To perhaps give you an idea of how I may have proceeded I found an [example of a test model](https://github.com/Foxy/foxy-elements/blob/44739f981ddcccfb149f5da13584f9788edbade3/src/elements/private/Switch/Switch.test.ts) which is how I was going to hack my tests to use the `meta` without putting `assert` into the production compiled source code files. Are you saying this is pointless?

In essence the test model is for e2e tests, where the underlying state engines are being used together with a view layer.

**Comment by davidkpiano** [comment]
> If I understand correctly it is pointless directly testing a state machine with `xstate/test`

The `@xstate/test` package does not dictate how you test your machines. You can test them directly; nothing is stopping you from doing so. However, it is not a best practice because typically, the system you're trying to model (with a state machine) is _different_ than the implementation details of that system.

Think of it this way: `@xstate/test` is a **model-based testing library**, _not_ a library for testing machines. It _uses_ machines to create models for model-based testing; its purpose isn't to _test_ those machines.

For testing machines, please see the docs: https://xstate.js.org/docs/guides/testing.html

**Comment by expelledboy** [comment]
Okay thanks. That is very clear. So you would test a model as per that guide, rather than creating a model based test?

I still feel the helper method would be useful. As [another example](https://github.com/ireneea/trivia/blob/77a254b53c11e1246fc8d55365ab0f6baeac4b87/src/Game/Game.model.test.js) I found demonstrates better what I was about to do, using the underlying state engine as part of the model based tests. Actually trying to reason about this however is beyond me at this stage.

In essence I have created a comprehensive, and without concrete implementations of actions, events, services etc state engine. Using this model I felt that I could generate an exhaustive list of unit tests from which I could assert the "implementation" rather than the model itself. There is definitely something I am missing, because it should be possible. But perhaps its best that I just follow a more linear approach as per the guide and just get this finished before the day is done.

Thanks :)
